#pragma once
// =============================================================================
//  net/bots — give bots real player names, live, while you play.
// =============================================================================
//
//  HOW IT WORKS, AND WHY IT CANNOT TOUCH A REAL PLAYER
//
//  The engine's own bot-add entry point already takes a name:
//
//      SV_AddBot(const char* name, unsigned int teamIndex)     IDA 0xF2650
//
//      if ( *a1 )                                 // a name WAS supplied
//          Com_sprintf(v34, 0x1F, "%s", a1);      //   use it verbatim, 31 max
//      else
//          v9 = SV_BotGetRandomName();            // else generate one
//      ...
//      sub_1052B0(Buffer, "connect bot%u \"%s\\name\\%s\\qport\\%d\\ctz\\%s\"");
//      sub_64C070(Buffer);                        // execute the connect
//      v20[67670] = 2;                            // 67670*4 = 270680 == isBot
//
//  TWIN-PROVEN against Advanced Warfare's symboled build, which exports the
//  mangled name outright:
//
//      ?SV_AddBot@@YAPAUgentity_s@@PBD@Z   ==  gentity_s* SV_AddBot(const char*)
//
//  and S2's returns `qword_BC6B8C8 + 1048*slot`, i.e. a gentity_s*. Same
//  function; S2 added a second parameter for the team/customization index.
//
//  ⭐ THE SAFETY GUARANTEE IS STRUCTURAL, NOT A RUNTIME CHECK.
//
//  A real player never reaches this function. Real clients arrive through
//  SV_DirectConnect from an actual network connect; SV_AddBot is only ever
//  called by the bot spawner (GSC `maps/mp/bots/_bots` -> the script builtin
//  sub_5A1B70 -> here). So hooking the BOT-ADD path rather than a rename path
//  means there is no code path by which a human's name could be rewritten.
//
//  That is much stronger than inspecting a client after the fact and deciding
//  whether it looks like a bot. We never have to make that judgement.
//
//  Belt and braces anyway: after the original returns, the new client's
//  isBot field (client + 270680) is READ BACK and reported. The engine sets it
//  to 2 for a bot. If it is ever anything else we say so loudly, because that
//  would mean the assumption above no longer holds.
//
//  ---------------------------------------------------------------------------
//  THE NAME LIST — the whole of your side of this
//  ---------------------------------------------------------------------------
//
//      <game dir>\botnames.txt      one name per line, '#' starts a comment
//
//  Created with instructions in it if missing. Reloaded automatically when its
//  timestamp changes, so you can edit it with the game running. Shuffled once
//  per match so the same list does not always come out in the same order, and
//  no name is used twice while a match is running.
//
//  Names are sanitised before use: the connect string is a userinfo string
//  (`\name\%s`), so a backslash or a quote inside a name would corrupt it.
//
//  ---------------------------------------------------------------------------
//  NOT DONE HERE (yet): emblem / calling card / prestige / level.
//
//  Those ride the same connect string as `\ctz\<serialized 28-byte struct>`,
//  built by sub_14B820 from the struct SV_AddBot fills at v31/v32/v33. Note
//  that SUPPLYING A NAME CHANGES WHICH BRANCH FILLS IT: with a name the engine
//  uses sub_14DAC0(&v31, Sys_Milliseconds()) rather than the per-team preset
//  sub_6F72A0(a2). So bot appearance may differ once renaming is on -- that is
//  expected, and controlling it is the next piece of work.
// =============================================================================

#include <cstddef>

namespace bots
{
	void init();

	// Are we renaming? False when the list is empty or the hook failed.
	[[nodiscard]] bool enabled();
	void set_enabled(bool on);

	// Re-read botnames.txt now. Returns the number of names loaded.
	std::size_t reload();

	[[nodiscard]] std::size_t name_count();
	[[nodiscard]] std::size_t renamed_count();

	// ---- appearance -----------------------------------------------------
	// Kits are read from <gamedir>\S2MP-Mod\botkits.txt, generated by
	// tools/s2_botkits.py from the game's own costume tables.
	[[nodiscard]] std::size_t kit_count();
	[[nodiscard]] std::size_t reload_kits();

	// 0 = off (engine default), 1 = copy the local player, 2 = one explicit
	// kit, 3 = random per bot with a percentage chance.
	[[nodiscard]] int  look_mode();
	[[nodiscard]] int  look_chance();
	void set_look_random(int percent);
	void set_look_off();

	// ---- the one button -------------------------------------------------
	// Turn on everything that makes a bot lobby look like a real one, in one
	// call: real names + a mixed spread of the game's own uniforms. The bot
	// COUNT is deliberately NOT part of this -- that stays the user's choice.
	void preset_lobby(int uniform_percent);

	// How many client slots exist and how many are taken. Returns false when no
	// server is running (so the GUI can say why instead of showing zeros).
	[[nodiscard]] bool slots(int& used, int& total);

	// True when SV_AddBot's hub gate is closed, i.e. bots cannot be added here.
	[[nodiscard]] bool in_hub();
}
