#pragma once

#include <array>
#include <string_view>

struct DvarMappingEntry {
	std::string_view user;
	std::string_view engine;
	std::string_view description;
};

namespace DvarMappings {
inline constexpr auto entries = std::to_array<DvarMappingEntry>({
	{ "accessToSubscriberContent", "838", "Whether to display the subscriber maps." },
	{ "ae_dropGameEventsWithDispatchType", "5805", "" },
	{ "ae_dropGameEventsWithID", "5826", "" },
	{ "ae_forceAllEventsDispatchType", "25", "" },
	{ "ae_minBufferingTimeForHFEvents", "1778", "" },
	{ "ai_corpseLimit", "ai_corpseLimit", "" },
	{ "aim_accel_turnrate_enabled", "1922", "Enable/disable acceleration of the turnrates" },
	{ "aim_lockon_enabled", "387", "Aim lock on helps the player to stay on target" },
	{ "allow_hub_vendor_menu", "allow_hub_vendor_menu", "" },
	{ "band_12players", "3829", "12 player bandwidth req'd" },
	{ "band_18players", "889", "18 player bandwidth req'd" },
	{ "band_2players", "357", "2 player bandwidth req'd" },
	{ "band_4players", "2237", "4 player bandwidth req'd" },
	{ "band_8players", "2871", "8 player bandwidth req'd" },
	{ "band_lotsplayers", "4342", "" },
	{ "bg_bombingRunNoMissileClip", "934", "" },
	{ "bg_shieldHitEncodeHeightVM", "1140", "The decoding range, in height, of a client's viewmodel shield." },
	{ "bg_shieldHitEncodeHeightWorld", "1612", "The encoding range, in height, of a client's world shield.  A hit in this range is encoded into one of 8 rows." },
	{ "bg_shieldHitEncodeWidthVM", "4078", "The decoding range, in width, of a client's viewmodel shield." },
	{ "bg_shieldHitEncodeWidthWorld", "3901", "The encoding range, in width, of a client's world shield.  A hit in this range is encoded into one of 16 columns." },
	{ "bg_shock_fadeOverride", "3712", "" },
	{ "bg_shock_lookControl", "1607", "" },
	{ "bg_shock_lookControl_fadeTime", "1824", "" },
	{ "bg_shock_lookControl_maxpitchspeed", "2670", "" },
	{ "bg_shock_lookControl_maxyawspeed", "667", "" },
	{ "bg_shock_lookControl_mousesensitivityscale", "1378", "" },
	{ "bg_shock_movement", "4216", "" },
	{ "bg_shock_screenBlurBlendFadeTime", "5644", "" },
	{ "bg_shock_screenBlurBlendTime", "4103", "" },
	{ "bg_shock_screenFlashShotFadeTime", "4531", "" },
	{ "bg_shock_screenFlashWhiteFadeTime", "5375", "" },
	{ "bg_shock_screenType", "2748", "" },
	{ "bg_shock_sound", "4269", "" },
	{ "bg_shock_soundDryLevel", "1262", "" },
	{ "bg_shock_soundEnd", "2839", "" },
	{ "bg_shock_soundEndAbort", "1455", "" },
	{ "bg_shock_soundFadeInTime", "304", "" },
	{ "bg_shock_soundFadeOutTime", "2931", "" },
	{ "bg_shock_soundLoop", "1270", "" },
	{ "bg_shock_soundLoopEndDelay", "3375", "" },
	{ "bg_shock_soundLoopFadeTime", "954", "" },
	{ "bg_shock_soundLoopSilent", "753", "" },
	{ "bg_shock_soundModEndDelay", "2010", "" },
	{ "bg_shock_soundRoomType", "3620", "" },
	{ "bg_shock_soundSubmix", "3744", "" },
	{ "bg_shock_soundWetLevel", "1397", "" },
	{ "bg_shock_viewKickFadeTime", "1407", "" },
	{ "bg_shock_viewKickPeriod", "3856", "" },
	{ "bg_shock_viewKickRadius", "3850", "" },
	{ "bg_turretIgnoreAttachedEnt", "bg_turretIgnoreAttachedEnt", "" },
	{ "breadcrumbdata_active", "466", "" },
	{ "breadcrumbdata_frequency_seconds", "34", "" },
	{ "breadcrumbdata_maxcompressionbuffer", "4030", "" },
	{ "ca_auto_signin", "5570", "CoD Anywhere start sign-in task automatically on startup or first party sign-in" },
	{ "ca_do_mlc", "1966", "CoD Anywhere Do Multi Login check" },
	{ "ca_intra_only", "3302", "CoD Anywhere Intra Network Only" },
	{ "ca_require_signin", "2520", "CoD Anywhere require sign in to enter MP" },
	{ "cachedContentDebug", "4279", "" },
	{ "camera_thirdPerson", "311", "se third person view globally" },
	{ "cameraShakeRemoteHelo_Angles", "3086", "" },
	{ "cameraShakeRemoteHelo_Freqs", "4780", "" },
	{ "cameraShakeRemoteHelo_SpeedRange", "1157", "" },
	{ "cameraShakeRemoteMissile_Angles", "4141", "" },
	{ "cameraShakeRemoteMissile_Freqs", "4275", "" },
	{ "cameraShakeRemoteMissile_SpeedRange", "5243", "" },
	{ "cg_airstrikeCamFstop", "3160", "Airstrike kill camera aperture. Lower f-stop yields a shallower depth of field. Typical values range from 1 to 22" },
	{ "cg_airstrikeKillCamFarBlur", "3822", "" },
	{ "cg_airstrikeKillCamFarBlurDist", "4446", "" },
	{ "cg_airstrikeKillCamFarBlurStart", "5493", "" },
	{ "cg_airstrikeKillCamFov", "3720", "" },
	{ "cg_airstrikeKillCamNearBlur", "3706", "" },
	{ "cg_airstrikeKillCamNearBlurEnd", "5095", "" },
	{ "cg_airstrikeKillCamNearBlurStart", "5840", "" },
	{ "cg_altimeterCenter", "cg_altimeterCenter", "" },
	{ "cg_altimeterRange", "cg_altimeterRange", "" },
	{ "cg_blood", "cg_blood", "Show Blood" },
	{ "cg_brass", "3385", "Weapons eject brass" },
	{ "cg_broadcasterSkycamDistance", "3119", "" },
	{ "cg_cameraShakesAffectVehicleCamera", "3268", "" },
	{ "cg_chatHeight", "2662", "The font height of a chat message" },
	{ "cg_chatTime", "804", "The amount of time that a chat message is visible" },
	{ "cg_clientViewAspect0", "cg_clientViewAspect0", "" },
	{ "cg_clientViewAspect1", "cg_clientViewAspect1", "" },
	{ "cg_compassClippedEnemyAlphaClose", "509", "" },
	{ "cg_compassClippedEnemyAlphaFar", "613", "" },
	{ "cg_compassClippedEnemyAlphaMedium", "1022", "" },
	{ "cg_compassClippedEnemyDistanceClose", "2283", "" },
	{ "cg_compassClippedEnemyDistanceMedium", "92", "" },
	{ "cg_compassClippedEnemyIconScale", "3607", "" },
	{ "cg_compassEnemyDrawMode", "4530", "" },
	{ "cg_compassScorestreakUseSelfColor", "5837", "" },
	{ "cg_compassTrailExplosiveFadeDur", "1030", "" },
	{ "cg_compassTrailExplosiveItemDist", "4045", "" },
	{ "cg_compassTrailExplosiveMaxScale", "2624", "" },
	{ "cg_compassTrailExplosiveMinScale", "4718", "" },
	{ "cg_compassTrailExplosiveNumItems", "1914", "" },
	{ "cg_compassTrailExplosiveRandScaleOffset", "4641", "" },
	{ "cg_compassTrailExplosiveRandScaleRange", "3789", "" },
	{ "cg_compassTrailFireFadeDur", "5604", "" },
	{ "cg_compassTrailFireItemDist", "4244", "" },
	{ "cg_compassTrailFireMaxScale", "35", "" },
	{ "cg_compassTrailFireMinScale", "4997", "" },
	{ "cg_compassTrailFireNumItems", "2036", "" },
	{ "cg_compassTrailFireRandScaleOffset", "1082", "" },
	{ "cg_compassTrailFireRandScaleRange", "3497", "" },
	{ "cg_crosshairAlpha", "2105", "" },
	{ "cg_crosshairAlphaMin", "4967", "" },
	{ "cg_crosshairDynamic", "2700", "" },
	{ "cg_crosshairEnemyColor", "3165", "" },
	{ "cg_cullBulletAngle", "3507", "Cull bullet trajectories that don't fall within this fov" },
	{ "cg_cullBullets", "4949", "Whether to cull bullet fire prediction if trajectory doesn't pass your view or anywhere near you" },
	{ "cg_cursorHints", "4521", "Draw cursor hints where: 0: no hints 1 : sin size pulse 2 : one way size pulse 3 : alpha pulse 4 : static image" },
	{ "cg_deadChatWithDead", "2651", "If true, dead players can all chat together, regardless of team" },
	{ "cg_deadChatWithTeam", "3328", "If true, dead players can talk to living players on their team" },
	{ "cg_deadHearAllLiving", "558", "If true, dead players can hear all living players talk" },
	{ "cg_deadHearTeamLiving", "1176", "If true, dead players can hear living players on their team talk" },
	{ "cg_debugRootMotionLog", "3343", "" },
	{ "cg_descriptiveText", "4666", "" },
	{ "cg_disableScreenShake", "3926", "Turns off screen shakes when turned on. Dev-only" },
	{ "cg_draw2D", "2562", "Draw 2D screen elements" },
	{ "cg_drawBreathHint", "863", "Draw a 'hold breath to steady' hint" },
	{ "cg_drawBreathHUD", "1668", "" },
	{ "cg_drawCrosshair", "1874", "Turn on weapon crosshair" },
	{ "cg_drawCrosshairNames", "1979", "Draw the name of an enemy under the crosshair" },
	{ "cg_drawDamageDirection", "883", "Draw hit direction arrow." },
	{ "cg_drawDamageFlash", "221", "Draw flash when hit." },
	{ "cg_drawDoubleTapDetonateHint", "1784", "Draw a 'double tap to detonate grenade' hint" },
	{ "cg_drawFriendlyHUDGrenades", "4466", "" },
	{ "cg_drawFriendlyNames", "1380", "Whether to show friendly names in game" },
	{ "cg_drawFriendlyNamesAlways", "4934", "" },
	{ "cg_drawGun", "1762", "Draw the view model" },
	{ "cg_drawMantleHint", "2104", "Draw a 'press key to mantle' hint" },
	{ "cg_drawpaused", "3496", "" },
	{ "cg_drawTurretCrosshair", "5771", "" },
	{ "cg_drawVehicleCrosshair", "cg_drawVehicleCrosshair", "" },
	{ "cg_errordecay", "4391", "Decay for predicted error" },
	{ "cg_everyoneHearsEveryone", "3724", "If true, all players can all chat together, regardless of team or death" },
	{ "cg_explosiveKillCamBackDist", "3692", "" },
	{ "cg_explosiveKillCamUpDist", "1321", "" },
	{ "cg_fakeSafeSKU", "5468", "" },
	{ "cg_flashbangNameFadeIn", "5860", "Time in milliseconds to fade in friendly names after a flashbang" },
	{ "cg_flashbangNameFadeOut", "3428", "Time in milliseconds to fade out friendly names when flash banged" },
	{ "cg_foliagesnd_alias", "4011", "" },
	{ "cg_footsteps", "4291", "Play footstep sounds that are NOT sprint" },
	{ "cg_fov", "cg_fov", "" },
	{ "cg_fov_intermission", "cg_fov_intermission", "" },
	{ "cg_fov1", "cg_fov1", "" },
	{ "cg_fovMin", "361", "The minimum possible field of view" },
	{ "cg_fovScale", "3078", "Scale applied to the field of view" },
	{ "cg_friendlyNameFadeIn", "3768", "Time in milliseconds to fade in friendly names" },
	{ "cg_friendlyNameFadeOut", "5344", "Time in milliseconds to fade out friendly names" },
	{ "cg_gameBoldMessageWidth", "4916", "" },
	{ "cg_gameMessageWidth", "5279", "" },
	{ "cg_gunReticleTeamColor_EnemyTeam", "4426", "" },
	{ "cg_gunReticleTeamColor_MyTeam", "4893", "" },
	{ "cg_hearVictimEnabled", "3452", "" },
	{ "cg_hearVictimTime", "408", "" },
	{ "cg_heliKillCamFarBlur", "693", "" },
	{ "cg_heliKillCamFarBlurDist", "5782", "" },
	{ "cg_heliKillCamFarBlurStart", "5721", "" },
	{ "cg_heliKillCamFov", "37", "Helicopter kill camera field of view." },
	{ "cg_heliKillCamFstop", "1136", "" },
	{ "cg_heliKillCamNearBlur", "1863", "" },
	{ "cg_heliKillCamNearBlurEnd", "5460", "" },
	{ "cg_heliKillCamNearBlurStart", "3000", "" },
	{ "cg_hintFadeTime", "310", "Time in milliseconds for the cursor hint to fade" },
	{ "cg_hubTransitionLerpTime", "3993", "" },
	{ "cg_hubZoomDist", "861", "" },
	{ "cg_hubZoomDoFDist", "1108", "" },
	{ "cg_hubZoomDoFfStop", "652", "" },
	{ "cg_hubZoomEnabled", "4990", "" },
	{ "cg_hubZoomFov", "4444", "" },
	{ "cg_hubZoomLerpTime", "2596", "" },
	{ "cg_hudChatIntermissionPosition", "4228", "" },
	{ "cg_hudChatPosition", "2563", "" },
	{ "cg_hudDamageIconHeight", "4434", "" },
	{ "cg_hudDamageIconInScope", "4366", "" },
	{ "cg_hudDamageIconTime", "4869", "" },
	{ "cg_hudDamageIconWidth", "2858", "" },
	{ "cg_hudGrenadeIconEnabledFlash", "4876", "" },
	{ "cg_hudGrenadeIconHeight", "1806", "" },
	{ "cg_hudGrenadeIconInScope", "5259", "" },
	{ "cg_hudGrenadeIconMaxRangeFlash", "4356", "" },
	{ "cg_hudGrenadeIconMaxRangeFrag", "787", "" },
	{ "cg_hudGrenadeIconMinScale", "2385", "" },
	{ "cg_hudGrenadeIconOffset", "2772", "" },
	{ "cg_hudGrenadeIconShowFuse", "4727", "" },
	{ "cg_hudGrenadeIconWidth", "1310", "" },
	{ "cg_hudGrenadePointerHeight", "4217", "" },
	{ "cg_hudGrenadePointerOffset", "416", "" },
	{ "cg_hudGrenadePointerPivot", "2913", "" },
	{ "cg_hudGrenadePointerWidth", "2777", "" },
	{ "cg_hudGrenadeScreenCornerPadding", "1370", "" },
	{ "cg_hudGrenadeScreenEdgePadding", "2246", "" },
	{ "cg_hudLegacySplitscreenScale", "4517", "" },
	{ "cg_hudMapBorderWidth", "701", "" },
	{ "cg_hudMapFriendlyHeight", "714", "" },
	{ "cg_hudMapFriendlyWidth", "796", "" },
	{ "cg_hudMapPlayerHeight", "1428", "" },
	{ "cg_hudMapPlayerWidth", "4685", "" },
	{ "cg_hudMapRadarLineThickness", "4365", "Thickness, relative to the map width, of the radar texture that sweeps across the full screen map" },
	{ "cg_hudObjectiveTextScale", "cg_hudObjectiveTextScale", "" },
	{ "cg_hudSayPosition", "2815", "Position of the HUD chat box during intermission" },
	{ "cg_hudSplitscreenCompassElementScale", "4041", "" },
	{ "cg_hudSplitscreenCompassScale", "1888", "" },
	{ "cg_hudSplitscreenOffsetsUseScale", "454", "" },
	{ "cg_invalidCmdHintBlinkInterval", "811", "Blink rate of an invalid command hint" },
	{ "cg_invalidCmdHintDuration", "641", "Duration of an invalid command hint" },
	{ "cg_killCamDefaultLerpTime", "2254", "" },
	{ "cg_killCamTurretLerpTime", "5831", "" },
	{ "cg_landingSounds", "4440", "" },
	{ "cg_mapLocationSelectionCursorSpeed", "281", "" },
	{ "cg_marks_ents_player_only", "4775", "" },
	{ "cg_maxAttachmentDisplays", "5441", "" },
	{ "cg_minCullBulletDist", "5562", "" },
	{ "cg_overheadNamesFarDist", "2393", "The far distance at which name sizes are scaled by cg_overheadNamesFarScale" },
	{ "cg_overheadNamesFarScale", "1900", "The amount to scale overhead name sizes at cg_overheadNamesFarDis" },
	{ "cg_overheadNamesFont", "731", "Font for overhead names" },
	{ "cg_overheadNamesGlow", "257", "Glow color for overhead names" },
	{ "cg_overheadNamesNearDist", "1733", "The near distance at which names are full size" },
	{ "cg_processImmediateEvents", "2921", "" },
	{ "cg_remoteCameraZNear", "4317", "" },
	{ "cg_ScorestreakColor_Enemy", "2906", "" },
	{ "cg_showmiss", "4645", "Show prediction errors" },
	{ "cg_subtitleColor", "2191", "" },
	{ "cg_subtitleForcedColor", "5004", "" },
	{ "cg_subtitleMinTime", "2986", "" },
	{ "cg_subtitleWidthStandard", "4834", "" },
	{ "cg_subtitleWidthWidescreen", "1003", "" },
	{ "cg_teamChatsOnly", "1127", "Allow chatting only on the same team" },
	{ "cg_tweenExtrapolationPeriodMs", "5173", "" },
	{ "cg_tweenOverridePeriodMs", "1906", "" },
	{ "cg_tweenOverridePeriodSlowMs", "2778", "" },
	{ "cg_tweenOverrideThresholdMs", "4088", "" },
	{ "cg_vectorFieldsForceUniform", "2895", "" },
	{ "cg_vehicleVMFovScaling", "2328", "" },
	{ "cg_viewAnglePitchScale", "4877", "" },
	{ "cg_viewVehicleInfluence", "3019", "The influence on the view angles from being in a vehicle" },
	{ "cg_viewZSmoothingMax", "2391", "Threshhold for the maximum smoothing distance we'll do" },
	{ "cg_viewZSmoothingMin", "5640", "Threshhold for the minimum smoothing distance it must move to smooth" },
	{ "cg_viewZSmoothingTime", "957", "Amount of time to spread the smoothing over" },
	{ "cg_weapHitCullAngle", "207", "Angle of cone within which to cull back facing weapon hit effects" },
	{ "cg_weapHitCullEnable", "5446", "When true, cull back facing weapon hit fx." },
	{ "cg_weapon_charm_killswitch", "cg_weapon_charm_killswitch", "" },
	{ "cg_weaponCycleDelay", "3891", "" },
	{ "cg_weaponHintsCoD1Style", "629", "Draw weapon hints in CoD1 style: with the weapon name, and with the icon below" },
	{ "cg_weaponVisInterval", "412", "Do weapon vis checks once per this many frames, per centity" },
	{ "cl_force_paused", "1265", "Force the client to be paused. Can't be overridden by LUA scripts, the start button, etc." },
	{ "cl_modifiedDebugPlacement", "2303", "Modify the location of debug output (outside of safe area)" },
	{ "cl_paused", "183", "Pause the game" },
	{ "clientNetPerf_enabled", "1427", "" },
	{ "clientNetPerf_UserCmdDroppedMinCount", "2614", "" },
	{ "clientNetPerf_UserCmdProcessedMinCount", "5040", "" },
	{ "clientNetPerf_UserCmdQueuedMinCount", "4912", "" },
	{ "clientNetPerf_UserCmdTimeWindowMs", "156", "" },
	{ "clientscript_debugPrint", "2995", "" },
	{ "clientSideEffects", "3508", "" },
	{ "com_animCheck", "1790", "Check anim tree" },
	{ "com_cinematicEndInWhite", "2196", "" },
	{ "com_completionResolveCommand", "5369", "" },
	{ "com_errorMessage", "1943", "" },
	{ "com_errorRemoveKeyCatcher", "5071", "" },
	{ "com_errorResolveCommand", "4278", "Command to run when they close the error box" },
	{ "com_errorTitle", "1278", "" },
	{ "com_filter_output", "2919", "Use console filters for filtering output." },
	{ "com_graphicsTier", "com_graphicsTier", "" },
	{ "com_maxfps", "com_maxfps", "Cap frames per second" },
	{ "com_maxFrameTime", "1292", "Time slows down if a frame takes longer than this many milliseconds" },
	{ "com_setRecommendedPass", "com_setRecommendedPass", "" },
	{ "combatRolesEnabled", "1936", "" },
	{ "compassClampIcons", "2980", "If true, friendlies and enemy pings clamp to the edge of the radar.  If false, they disappear off the edge." },
	{ "compassFriendlyHeight", "784", "The size of the friendly icon on the compass" },
	{ "compassFriendlyWidth", "4963", "The size of the friendly icon on the compass" },
	{ "compassHideVehicles", "965", "" },
	{ "compassObjectiveArrowHeight", "660", "" },
	{ "compassObjectiveDetailDist", "3934", "" },
	{ "compassObjectiveIconHeight", "2617", "" },
	{ "compassObjectiveIconWidth", "2483", "" },
	{ "compassObjectiveMaxRange", "3565", "" },
	{ "compassObjectiveMinAlpha", "5258", "" },
	{ "compassPlayerHeight", "2430", "" },
	{ "compassPlayerWidth", "3340", "" },
	{ "compassPrototypeElevation", "3500", "" },
	{ "compassPrototypeFiring", "4129", "" },
	{ "compassRadarLineThickness", "3967", "" },
	{ "compassRadarPingFadeTime", "4811", "" },
	{ "compassRotation", "4433", "" },
	{ "compassSize", "2692", "Scale the compass" },
	{ "compassSoundPingFadeTime", "5111", "" },
	{ "compassTickertapeStretch", "66", "" },
	{ "comscore_backoff", "3219", "constants for the comscore backoff function a*(x-b)^2+c" },
	{ "core_mp_weaponorder_killswitch", "core_mp_weaponorder_killswitch", "" },
	{ "dc_lobbymerge", "3583", "Allows lobby merging across data centres" },
	{ "dcacheThrottleEnabled", "1126", "" },
	{ "dcacheThrottleKBytesPerSec", "1945", "" },
	{ "dedicated_dhclient", "1591", "" },
	{ "dev_auto_hubstart", "3708", "Auto load the game into the MP hub" },
	{ "developer", "1147", "" },
	{ "dive_exhaustion_window", "4075", "" },
	{ "dlc2_killswitch", "dlc2_killswitch", "" },
	{ "dlc3_killswitch", "dlc3_killswitch", "" },
	{ "dlc4_killswitch", "dlc4_killswitch", "" },
	{ "dlog_active", "5785", "" },
	{ "dlog_devpointHost", "5138", "" },
	{ "ds_pingclient_maxpings", "5636", "max pings to send per datacenter" },
	{ "ds_pingclient_maxpings_per_tick", "1461", "max new pings each tick" },
	{ "ds_pingclient_minpings", "4091", "min responses required per datacenter" },
	{ "ds_pingclient_odsf", "4492", "does dsping set odsf flag" },
	{ "dw_datachannel_umbrellaExpiryTimeOffset", "4194", "" },
	{ "dw_datachannel_umbrellaRetryTime", "3436", "" },
	{ "dw_enable_connection_telemetry", "1799", "" },
	{ "dw_interleave_all_nat_types", "3358", "" },
	{ "dw_nattrav_cache_enable", "770", "" },
	{ "dw_nattrav_cache_timeout", "463", "" },
	{ "dw_presence_active", "4174", "Is the demonware presence system enabled" },
	{ "dw_presence_coop_join", "418", "Do we allow players to join on presence for private coop matches (post session to demonware)" },
	{ "dw_presence_get_rate", "3602", "Number of milliseconds to wait between fetching presence state from demonware" },
	{ "dw_presence_put_delay", "3550", "Number of milliseconds to wait in a presence state before sending to demonware" },
	{ "dw_presence_put_rate", "561", "Number of milliseconds to wait between sending presence state to demonware" },
	{ "e3demo", "2803", "" },
	{ "e3demo_client", "1303", "" },
	{ "e3demo_host", "4605", "" },
	{ "e3demo_mapset", "4794", "" },
	{ "e3demo_show_client_title_screen", "871", "" },
	{ "elite_clan_active", "3629", "Are we allowed to show Elite Clans or not" },
	{ "elite_clan_cool_off_time", "5281", "" },
	{ "elite_clan_delay", "2672", "Delay before the bdTeams calls start to Demonware. -1 means On-Demand and it will wait until the 'starteliteclan' menu call" },
	{ "elite_clan_get_blob_profile_max_retry_time", "4136", "" },
	{ "elite_clan_get_blob_profile_retry_step", "813", "" },
	{ "elite_clan_get_clan_max_retry_time", "4416", "" },
	{ "elite_clan_get_clan_retry_step", "1092", "" },
	{ "elite_clan_get_members_max_retry_time", "4619", "" },
	{ "elite_clan_get_members_retry_step", "2452", "" },
	{ "elite_clan_get_private_member_profile_max_retry_time", "53", "" },
	{ "elite_clan_get_private_member_profile_retry_step", "834", "" },
	{ "elite_clan_get_public_profile_max_retry_time", "1574", "" },
	{ "elite_clan_get_public_profile_retry_step", "2257", "" },
	{ "elite_clan_motd_throttle_time", "2209", "" },
	{ "elite_clan_remote_view_active", "5205", "" },
	{ "elite_clan_remote_view_max_retry_time", "5560", "" },
	{ "elite_clan_remote_view_retry_step", "434", "" },
	{ "elite_clan_send_message_to_members_max_retry_time", "643", "" },
	{ "elite_clan_send_message_to_members_rerty_step", "4237", "" },
	{ "elite_clan_set_private_member_profile_max_retry_time", "636", "" },
	{ "elite_clan_set_private_member_profile_retry_step", "2655", "" },
	{ "elite_clan_single_task_popup_text", "2592", "" },
	{ "elite_clan_upload_emblemunlock_enable", "2849", "" },
	{ "elite_clan_using_title", "4106", "" },
	{ "emblems_active", "4798", "Are we allowed to enable Emblems or not" },
	{ "enericIconAlphaFadeTime", "3630", "" },
	{ "facebook_active", "4761", "Are we allowed to show Facebook or not" },
	{ "facebook_delay", "1636", "Delay before the Facebook calls start to Demonware. -1 means On-Demand and it will wait until the 'startfacebook' menu call" },
	{ "facebook_friends_active", "2687", "" },
	{ "facebook_friends_max_retry_time", "339", "" },
	{ "facebook_friends_refresh_time", "5238", "" },
	{ "facebook_friends_retry_step", "2306", "" },
	{ "facebook_friends_showing_count", "3860", "" },
	{ "facebook_friends_throttle_time", "5232", "" },
	{ "facebook_max_retry_time", "5797", "Max time that the Facebook authentication can retry" },
	{ "facebook_password", "4776", "" },
	{ "facebook_password_asterisk", "4591", "" },
	{ "facebook_popup_text", "2744", "" },
	{ "facebook_retry_step", "4142", "Step in m/s for the Facebook authentication retry" },
	{ "facebook_upload_photo_active", "5141", "" },
	{ "facebook_upload_video_active", "2688", "" },
	{ "facebook_username", "4323", "" },
	{ "fd_enable_fbw", "fd_enable_fbw", "" },
	{ "fd_pause_update", "fd_pause_update", "" },
	{ "ffotdUpdateCheckMinutes", "5168", "" },
	{ "fighter_vs_fighter_mode", "fighter_vs_fighter_mode", "" },
	{ "fixedtime", "299", "Use a fixed time rate for each frame" },
	{ "FoFIconMaxSize", "3439", "" },
	{ "FoFIconMinSize", "1401", "" },
	{ "FoFIconScale", "618", "" },
	{ "FoFIconSpawnTimeDelay", "1112", "" },
	{ "FoFIconSpawnTimeFade", "1555", "" },
	{ "framesToWaitForVLobbyErrors", "framesToWaitForVLobbyErrors", "" },
	{ "fs_basegame", "2796", "Base game name" },
	{ "fs_basepath", "4972", "Base game path" },
	{ "fs_debug", "1467", "Enable file system debugging information" },
	{ "fs_game", "1751", "Game data directory. Must be \"\" or a sub directory of 'mods/'." },
	{ "fs_homepath", "4068", "Game home path" },
	{ "fs_ignoreLocalized", "3139", "Ignore localized files" },
	{ "fte_demo", "5737", "" },
	{ "fte_progress", "1471", "" },
	{ "fx_alphaThreshold", "3541", "Don't draw billboard sprites, oriented sprites or tails with alpha below this threshold (0-256)." },
	{ "fx_cast_shadow", "2527", "Enable transparency shadow mapping from script" },
	{ "fx_deferelem", "452", "Toggles deferred processing of elements instead of effects" },
	{ "fx_draw", "3461", "Toggles drawing of effects after processing" },
	{ "fx_draw_omniLight", "5408", "Toggles drawing of effects after processing" },
	{ "fx_draw_spotLight", "2157", "Toggles drawing of effects after processing" },
	{ "fx_drawClouds", "1398", "Toggles the drawing of particle clouds" },
	{ "fx_dynamicGritDisableBlood", "543", "" },
	{ "fx_dynamicGritDisableFire", "1487", "" },
	{ "fx_dynamicGritDisableHide", "5442", "" },
	{ "fx_enable", "3917", "Toggles all effects processing" },
	{ "fx_killEffectOnRewind", "1666", "Causes effects that have been marked for a soft kill (fade out) to be killed immediately on a rewind." },
	{ "fx_lightgridplus_enable", "5637", "" },
	{ "fx_lightGridSampleOffset", "4525", "the length of effect sample's offset along X Axis" },
	{ "fx_lightmap_max_level", "557", "" },
	{ "fx_lightmap_pixels_per_texel", "3085", "" },
	{ "fx_marks", "4777", "Toggles whether bullet hits leave marks" },
	{ "fx_marks_ents", "3617", "Toggles whether bullet hits leave marks on entities" },
	{ "fx_marks_smodels", "4", "Toggles whether bullet hits leave marks on static models" },
	{ "fx_physicsImpactVelocityThreshold", "2224", "Set the min normal velocity threshold in order for model physics fx to generate child impact effects." },
	{ "fx_use_rewind_flags", "4994", "" },
	{ "fx_visMinTraceDist", "3344", "Minimum visibility trace size" },
	{ "g_atmosFogAirLightCapacityReadOnly", "4809", "" },
	{ "g_atmosFogAirLightDensityScalarReadOnly", "1509", "" },
	{ "g_atmosFogAirLightVertexInnerMutedRadiusReadOnly", "3042", "" },
	{ "g_atmosFogDistanceScaleReadOnly", "4540", "" },
	{ "g_atmosFogEnabledReadOnly", "3304", "" },
	{ "g_atmosFogEntityScaleReadOnly", "3465", "" },
	{ "g_atmosFogExtinctionDesaturationReadOnly", "1986", "" },
	{ "g_atmosFogExtinctionStrengthReadOnly", "468", "" },
	{ "g_atmosFogHalfPlaneDistanceReadOnly", "1025", "" },
	{ "g_atmosFogHazeColorReadOnly", "4577", "" },
	{ "g_atmosFogHazeSpreadReadOnly", "2554", "" },
	{ "g_atmosFogHazeStrengthReadOnly", "5702", "" },
	{ "g_atmosFogHeightFogBaseHeightReadOnly", "2053", "" },
	{ "g_atmosFogHeightFogEnabledReadOnly", "2644", "" },
	{ "g_atmosFogHeightFogHalfPlaneDistanceReadOnly", "837", "" },
	{ "g_atmosFogHeightFogMaximumOffsetReadOnly", "1876", "" },
	{ "g_atmosFogHeightFogStrengthOfDepthFogReadOnly", "3186", "" },
	{ "g_atmosFogInScatterStrengthReadOnly", "2768", "" },
	{ "g_atmosFogSkyAngularFalloffEnabledReadOnly", "927", "" },
	{ "g_atmosFogSkyDistanceReadOnly", "3728", "" },
	{ "g_atmosFogSkyFalloffAngleRangeReadOnly", "184", "" },
	{ "g_atmosFogSkyFalloffStartAngleReadOnly", "2062", "" },
	{ "g_atmosFogSplineCustomDistance1ReadOnly", "2183", "" },
	{ "g_atmosFogSplineCustomDistance2ReadOnly", "1393", "" },
	{ "g_atmosFogSplineCustomDistance3ReadOnly", "2411", "" },
	{ "g_atmosFogSplineCustomTangentAngle1ReadOnly", "638", "" },
	{ "g_atmosFogSplineCustomTangentAngle2ReadOnly", "5064", "" },
	{ "g_atmosFogSplineCustomTangentAngle3ReadOnly", "192", "" },
	{ "g_atmosFogSplineCustomTangentsEnabledReadOnly", "2805", "" },
	{ "g_atmosFogSplineCustomVisibility1ReadOnly", "1720", "" },
	{ "g_atmosFogSplineCustomVisibility2ReadOnly", "688", "" },
	{ "g_atmosFogSplineCustomVisibility3ReadOnly", "4313", "" },
	{ "g_atmosFogSplineEnabledReadOnly", "3698", "" },
	{ "g_atmosFogSplineMaxDistanceReadOnly", "4908", "" },
	{ "g_atmosFogSplineMaxDistanceTangentAngleReadOnly", "2050", "" },
	{ "g_atmosFogSplineMaxDistanceVisibilityOverrideReadOnly", "3335", "" },
	{ "g_atmosFogSplineMaxDistanceVisibilityReadOnly", "1392", "" },
	{ "g_atmosFogSplineStartingTangentAngleReadOnly", "26", "" },
	{ "g_atmosFogSplineUseMaxDistanceVisibilityOverrideReadOnly", "1031", "" },
	{ "g_atmosFogStartDistanceReadOnly", "2108", "" },
	{ "g_atmosFogSunDirectionReadOnly", "3809", "" },
	{ "g_atmosFogSunFogColorReadOnly", "1483", "" },
	{ "g_banIPs", "5370", "IP addresses to ban from playing" },
	{ "g_clonePlayerMaxVelocity", "4516", "" },
	{ "g_deadChat", "2335", "" },
	{ "g_dropForwardSpeed", "1346", "" },
	{ "g_dropHorzSpeedRand", "843", "" },
	{ "g_dropUpSpeedBase", "4470", "" },
	{ "g_dropUpSpeedRand", "178", "" },
	{ "g_earthquakeEnable", "3913", "" },
	{ "g_gametype", "1924", "The current game mode" },
	{ "g_inactivity", "2916", "Time delay before player is kicked for inactivity" },
	{ "g_knockback", "4541", "" },
	{ "g_lagged_damage_threshold", "3120", "" },
	{ "g_listEntity", "4831", "" },
	{ "g_mantleBlockTimeBuffer", "483", "" },
	{ "g_maxDroppedWeapons", "1605", "Maximum number of dropped weapons" },
	{ "g_minGrenadeDamageSpeed", "1794", "" },
	{ "g_password", "5370", "Password" },
	{ "g_scriptMainMenu", "g_scriptMainMenu", "" },
	{ "g_TeamName_Allies", "1202", "" },
	{ "g_TeamName_Axis", "2991", "" },
	{ "g_voiceChatTalkingDuration", "3992", "" },
	{ "gamescom_build", "2543", "" },
	{ "genericIconAlpha", "4783", "" },
	{ "glass_angular_vel", "3766", "Sets the range of angular velocities used by new glass pieces" },
	{ "glass_break", "2210", "Toggle whether or not glass breaks when shot" },
	{ "glass_crack_pattern_scale", "4887", "The scale applied to the radius used for the crack pattern" },
	{ "glass_edge_angle", "2449", "Sets the range of angle deflections used by new glass pieces on a supported edge" },
	{ "glass_fall_delay", "474", "glass_fall_delay" },
	{ "glass_fall_gravity", "2436", "Gravity for falling pieces of glass" },
	{ "glass_fall_ratio", "3991", "Ratio of piece area to supporting edge length squared.  Below the min, the piece never falls." },
	{ "glass_fringe_maxcoverage", "4886", "The maximum portion of the original piece of glass that is allowed to remain after the glass shatters" },
	{ "glass_fringe_maxsize", "5363", "The maximum area for an edge piece of glass when shattering. Pieces larger than this will be broken into smaller ones" },
	{ "glass_fx_chance", "2355", "Chance to play an effect on a small piece of glass when it hits the ground" },
	{ "glass_hinge_friction", "2848", "Friction used by moving glass pieces when joined like a hinge to a frame" },
	{ "glass_linear_vel", "3330", "Sets the range of linear velocities used by new glass pieces" },
	{ "glass_max_pieces_per_frame", "3251", "Maximum number of pieces to create in one frame. This is a guideline and not a hard limit." },
	{ "glass_max_shatter_fx_per_frame", "3958", "Maximum number of shatter effects to play in one frame This is a guideline and not a hard limit." },
	{ "glass_physics_chance", "3430", "The chance for a given shard of glass to use physics" },
	{ "glass_physics_maxdist", "436", "The maximum distance of a glass piece from the player to do physics" },
	{ "glass_shard_maxsize", "3595", "The maximum area for a flying piece of glass when shattering. Pieces larger than this will be broken into smaller ones" },
	{ "glass_shattered_scale", "1567", "The scale of the shattered glass material" },
	{ "glass_trace_interval", "2239", "The length of time, in milliseconds, between glass piece traces" },
	{ "groupDownloadInterval", "411", "" },
	{ "groupUploadIntervalDS", "3827", "" },
	{ "hiDef", "1916", "" },
	{ "hub_leaderboard_max_distance", "3296", "" },
	{ "hub_supply_drop_max_distance", "4143", "" },
	{ "hub_vendor_overhead_max_distance", "3924", "" },
	{ "hub_vendor_overhead_min_distance", "1647", "" },
	{ "hubcamera", "4014", "" },
	{ "hubTeam", "4135", "" },
	{ "hud_drawHud", "597", "" },
	{ "hudElemPausedBrightness", "4520", "" },
	{ "hudOutlineDuringADS", "2260", "" },
	{ "igs_td", "532", "Show Trial DLC" },
	{ "intro", "2464", "" },
	{ "inventory_addEntitlementsToLocalInventory", "3455", "" },
	{ "inventory_consumableExchangeRetryMax", "4108", "" },
	{ "inventory_enabled", "1506", "" },
	{ "inventory_enableEntitlementDLCScanning", "3170", "" },
	{ "inventory_enableRevoke", "4815", "" },
	{ "inventory_exchangeClientID", "2327", "" },
	{ "inventory_exchangeEnabled", "5050", "" },
	{ "inventory_exchangeMaxConsumablesPerBoot", "2110", "" },
	{ "inventory_exchangeRetryBaseMS", "1529", "" },
	{ "inventory_exchangeRetryByRound", "5063", "" },
	{ "inventory_exchangeRetryMax", "1889", "" },
	{ "inventory_excludeEntitlementDLCScanning", "5709", "" },
	{ "inventory_ignoreDWPushNotification_itemUpdate", "5044", "" },
	{ "inventory_numItemsPerPage", "inventory_numItemsPerPage", "" },
	{ "inventory_triggerExchangeOnContentMount", "1861", "" },
	{ "inventory_triggerExchangeOnStoreExit", "1600", "" },
	{ "iotd_active", "2623", "Is the IOTD system enabled" },
	{ "iotd_retry", "60", "Can the IOTD system retry fetching data from Demonware" },
	{ "IsCoDAccountUIEnabled", "565", "" },
	{ "IsCODPointsEnabled", "4670", "" },
	{ "IsDiskBuild", "5049", "" },
	{ "IsDLC1Enabled", "5953", "" },
	{ "IsdlcDivisionEnabled_ARTILLERY", "6017", "" },
	{ "IsdlcDivisionEnabled_COMMANDO", "6019", "" },
	{ "IsdlcDivisionEnabled_GRENADIER", "6020", "" },
	{ "IsdlcDivisionEnabled_RESISTANCE", "6021", "" },
	{ "IsdlcDivisionEnabled_SCOUT", "6018", "" },
	{ "IsEmblemEditorEnabled", "1611", "" },
	{ "IsEmblemGalleryEnabled", "5952", "" },
	{ "isEsportsMatch", "isEsportsMatch", "" },
	{ "IsGamescomForceRankedMatch", "5357", "" },
	{ "isMLGMatch", "isMLGMatch", "" },
	{ "IsMTX1Enabled", "5955", "" },
	{ "IsMTX2Enabled", "5954", "" },
	{ "latestDlcRelease", "4717", "" },
	{ "latestDlcReleaseOverride", "5755", "" },
	{ "lb_times_in_window", "3355", "Lobby throttling window amount" },
	{ "lb_window", "2163", "Lobby throttling window" },
	{ "leprechauns_enabled", "leprechauns_enabled", "" },
	{ "lfg_enabled", "2195", "" },
	{ "lfg_freeslot_advertise_cutoff", "3008", "" },
	{ "lfg_playlist_search_offset", "4609", "" },
	{ "localize_strings", "1699", "" },
	{ "log_host_migration_chance", "2574", "The % chance of host migration results telemetry" },
	{ "logitech_led", "logitech_led", "" },
	{ "lowAmmoWarningColor1", "646", "" },
	{ "lowAmmoWarningColor2", "5124", "" },
	{ "lowAmmoWarningNoAmmoColor1", "5600", "" },
	{ "lowAmmoWarningNoAmmoColor2", "5490", "" },
	{ "lowAmmoWarningNoReloadColor1", "3535", "" },
	{ "lowAmmoWarningNoReloadColor2", "173", "" },
	{ "lowAmmoWarningPulseFreq", "5703", "" },
	{ "lowAmmoWarningPulseMax", "11", "" },
	{ "lowAmmoWarningPulseMin", "1036", "" },
	{ "lui_disable_blur", "262", "Disable LUI blur" },
	{ "lui_draw_hints", "5270", "" },
	{ "lui_FFotDLocalLoadEnabled", "4373", "" },
	{ "lui_FFotDSupportEnabled", "4373", "Enables lui to update itself via the ffotd" },
	{ "lui_hud_motion_angle_ease_speed", "2690", "Hud motion ease percentage of degrees per second" },
	{ "lui_hud_motion_bob_scale", "5406", "Hud motion bob scale" },
	{ "lui_hud_motion_enabled", "42", "Enable hud motion" },
	{ "lui_hud_motion_perspective", "5345", "value for hud motion perspective transform in pixels" },
	{ "lui_hud_motion_rotation_max", "1033", "Hud motion rotation max" },
	{ "lui_hud_motion_rotation_scale", "386", "Hud motion rotation scale" },
	{ "lui_hud_motion_trans_ease_speed", "397", "Hud motion ease percentage of pixels per second" },
	{ "lui_hud_motion_translation_max", "4686", "Hud motion translation max" },
	{ "lui_hud_motion_translation_scale", "381", "lui_hud_motion_translation_scale" },
	{ "lui_hud_show_turret_ammo", "4329", "" },
	{ "LUI_MemErrorsFatal", "1626", "Out of memory errors cause drops when true, reinits the UI system if false" },
	{ "lui_menuFlowEnabled", "4436", "Enables LUI menu flow" },
	{ "lui_parse_notify_max_args", "lui_parse_notify_max_args", "" },
	{ "lui_splitscreenupscaling", "659", "Force splitscreen upscaling off/on (-1 off, 1 on) -- requires map change" },
	{ "lui_systemlink_menu", "1572", "Enables the LUI systemlink menu" },
	{ "lui_waitingforgavelmessagesconfirmed", "3210", "" },
	{ "lui_waitingfornetworktype", "2100", "" },
	{ "lui_waitingforonlinedatafetch_controller", "2457", "" },
	{ "LUI_WorkerCmdGC", "3886", "Dev-only flag to enable/disable LUI workerCmd GC thread" },
	{ "lui_xboxlive_menu", "3547", "Enables the LUI xboxlive menu" },
	{ "mapname", "1673", "" },
	{ "mapPackMPGroupFourFlags", "3418", "Map pack flags that comprise MP ala carte map pack 4" },
	{ "mapPackMPGroupFreeFlags", "380", "Map pack flags that comprise the free MP ala carte map pack" },
	{ "mapPackMPGroupOneFlags", "655", "Map pack flags that comprise MP ala carte map pack 1" },
	{ "mapPackMPGroupThreeFlags", "4380", "Map pack flags that comprise MP ala carte map pack 3" },
	{ "mapPackMPGroupTwoFlags", "5670", "Map pack flags that comprise MP ala carte map pack 2" },
	{ "marketing_refresh_time", "1543", "time in seconds to wait before refreshing marketing messages from demonware" },
	{ "match_making_telemetry_chance", "743", "The % chance of sending match making telemetry" },
	{ "matchdata_active", "967", "Are match data uploads enabled" },
	{ "matchdata_maxcompressionbuffer", "2660", "Max SP match data compression buffer to use (in bytes)" },
	{ "matchnetperf_active", "109", "" },
	{ "max_ping_threshold_good", "4332", "max ping value to be considered as good" },
	{ "max_ping_threshold_medium", "4760", "max ping value to be considered as medium" },
	{ "melee_debug", "4202", "" },
	{ "missileGlideBombRotationFallingDelay", "2447", "" },
	{ "missileGlideBombRotationFallingRate", "4644", "" },
	{ "missileRemoteFOV", "2727", "" },
	{ "motionTrackerBlurDuration", "1186", "" },
	{ "motionTrackerCenterX", "182", "" },
	{ "motionTrackerCenterY", "5006", "" },
	{ "motionTrackerPingFadeTime", "3531", "" },
	{ "motionTrackerPingPitchAddPerEnemy", "5477", "" },
	{ "motionTrackerPingPitchBase", "679", "" },
	{ "motionTrackerPingPitchNearby", "5435", "" },
	{ "motionTrackerPingSize", "5793", "" },
	{ "mtx10_killswitch", "mtx10_killswitch", "" },
	{ "mtx11_killswitch", "mtx11_killswitch", "" },
	{ "mtx12_killswitch", "mtx12_killswitch", "" },
	{ "mtx3_5_killswitch", "mtx3_5_killswitch", "" },
	{ "mtx3_killswitch", "mtx3_killswitch", "" },
	{ "mtx4_killswitch", "mtx4_killswitch", "" },
	{ "mtx5_killswitch", "mtx5_killswitch", "" },
	{ "mtx6_killswitch", "mtx6_killswitch", "" },
	{ "mtx7_killswitch", "mtx7_killswitch", "" },
	{ "mtx8_killswitch", "mtx8_killswitch", "" },
	{ "mtx9_killswitch", "mtx9_killswitch", "" },
	{ "net_latest_tween_threshold", "1907", "" },
	{ "net_read_tween_packets", "4773", "" },
	{ "net_write_tween_packets", "5801", "" },
	{ "nextmap", "4059", "Next map to play" },
	{ "nightVisionDisableEffects", "3628", "" },
	{ "nightVisionFadeInOutTime", "4625", "" },
	{ "nightVisionPowerOnTime", "4842", "" },
	{ "num_available_map_packs", "5942", "Number of map packs available for this platform" },
	{ "objectiveFontSize", "5129", "" },
	{ "objectiveHide", "432", "" },
	{ "objectiveTextOffsetY", "599", "" },
	{ "onlinegame", "2291", "" },
	{ "overrideNVGModelWithKnife", "5025", "When true, nightvision animations will attach the weapDef's knife model instead of the night vision goggles." },
	{ "paintshop_SendPartyState", "paintshop_SendPartyState", "" },
	{ "painVisionLerpOutRate", "84", "" },
	{ "painVisionTriggerHealth", "2349", "" },
	{ "party_alternateMapVoteStatus", "5675", "Alternate map vote progress" },
	{ "party_alwaysNeedReadyUp", "2890", "" },
	{ "party_divisionXPScale", "party_divisionXPScale", "" },
	{ "party_enableblacklist", "party_enableblacklist", "" },
	{ "party_firstSubpartyIndex", "1329", "Determines sort order and coloring of parties in lobbies.  Randomly set by code.  Dvar provided for debugging." },
	{ "party_followPartyHostOutOfGames", "3598", "" },
	{ "party_inactiveHeartbeatPeriod", "3871", "" },
	{ "party_initial_dlc_search_timer", "2645", "Time until DLC enabled search should show an error dialog suggesting the user consider going to non dlc search" },
	{ "party_IsLocalClientSelected", "4981", "" },
	{ "party_kickplayerquestion", "5858", "String to store the question about kicking the selected player" },
	{ "party_lobbyPlayerCount", "2770", "Number of players currently in the party/lobby in lobby format (x/y players)" },
	{ "party_maxPrivatePartyPlayers", "5321", "Max number of players allowed in a private party." },
	{ "party_maxTeamDiff", "2989", "Maximum difference allowed between teams before starting a match" },
	{ "party_membersMissingMapPack", "5862", "" },
	{ "party_needFullPartyReady", "2474", "" },
	{ "party_nextMapVoteStatus", "3562", "Next map vote progress" },
	{ "party_partyPlayerCount", "5010", "Number of players currently in the party/lobby in party format (x players in y's party)" },
	{ "party_partyPlayerCountNum", "5458", "Number of players currently in the party/lobby" },
	{ "party_playersCoop", "4036", "" },
	{ "party_playerVisible", "2881", "" },
	{ "party_privatePartyJoinsHub", "1672", "" },
	{ "party_randomMapVoteStatus", "3136", "Random map vote progress" },
	{ "party_rankXPScale", "party_rankXPScale", "" },
	{ "party_resume_dlc_search_timer", "2645", "Time until DLC enabled search should show an error dialog after it's been searching already and a player leaves" },
	{ "party_search_for_dlc_content", "3582", "" },
	{ "party_selectedIndex", "2201", "Current selected player index in the feeder." },
	{ "party_selectedIndexChangedTime", "354", "Time stamp in milliseconds when the selected index last changed." },
	{ "party_statusString", "3633", "Party Status (localized )" },
	{ "party_teambased", "928", "" },
	{ "party_teamsVisible", "5174", "" },
	{ "party_timer", "5842", "Time until game begins in seconds, for UI display" },
	{ "party_weaponXPScale", "party_weaponXPScale", "" },
	{ "party_zmXPScale", "party_zmXPScale", "" },
	{ "partyCoopMatchmakingDelay", "216", "" },
	{ "partymigrate_broadcast_interval", "1843", "" },
	{ "partymigrate_logResults", "3615", "" },
	{ "partymigrate_makeHostTimeout", "5247", "" },
	{ "partymigrate_pingtest_active", "4473", "" },
	{ "partymigrate_pingtest_filterThreshold", "5735", "" },
	{ "partymigrate_pingtest_minThreshold", "4875", "" },
	{ "partymigrate_pingtest_retry", "232", "" },
	{ "partymigrate_pingtest_timeout", "54", "" },
	{ "partymigrate_selectiontime", "548", "" },
	{ "partymigrate_timeout", "4637", "" },
	{ "partymigrate_timeoutmax", "2248", "" },
	{ "partymigrate_uploadtest_minThreshold", "3879", "" },
	{ "patchmanifestoverride", "2363", "" },
	{ "patchManifestUpdateDisabled", "3990", "" },
	{ "patchmanifestversionoverride", "5546", "" },
	{ "patchSystemDebug", "3179", "" },
	{ "perk_bulletSuperPenetrationMultiplier", "perk_bulletSuperPenetrationMultiplier", "" },
	{ "perk_extendedMagsMGAmmo", "4114", "Number of extra bullets per clip for machine gun weapons with the extended mags perk." },
	{ "perk_extendedMagsPistolAmmo", "3112", "Number of extra bullets per clip for spread weapons with the extended mags perk." },
	{ "perk_extendedMagsRifleAmmo", "4722", "Number of extra bullets per clip for rifle weapons with the extended mags perk." },
	{ "perk_extendedMagsSMGAmmo", "2341", "Number of extra bullets per clip for sub machine gun weapons with the extended mags perk." },
	{ "perk_extendedMagsSniperAmmo", "3101", "Number of extra bullets per clip for sniper rifle weapons with the extended mags perk." },
	{ "perk_fastClimb", "2810", "" },
	{ "perk_fastSnipeScale", "364", "" },
	{ "perk_grenadeDeath", "2984", "Name of the grenade weapon to drop" },
	{ "perk_lightWeightViewBobScale", "2847", "" },
	{ "perk_numExtraLethal", "1477", "Number of extra lethal grenades" },
	{ "perk_numExtraTactical", "1410", "Number of extra tactical grenades" },
	{ "perk_parabolicAngle", "2277", "" },
	{ "perk_parabolicIcon", "1761", "Eavesdrop icon to use when displaying eavesdropped voice chats" },
	{ "perk_parabolicRadius", "2789", "" },
	{ "perk_quickDrawSpeedScale", "4314", "" },
	{ "perk_quickDrawSpeedScaleSniper", "1587", "" },
	{ "perk_sprintMultiplier", "885", "" },
	{ "phys_autoDisableTime", "5130", "" },
	{ "phys_bulletSpinScale", "4747", "" },
	{ "phys_bulletUpBias", "2295", "" },
	{ "phys_dragAngular", "100", "" },
	{ "phys_dragLinear", "1522", "" },
	{ "phys_gravity", "4290", "" },
	{ "physVeh_jump", "713", "" },
	{ "pickupPrints", "1017", "" },
	{ "player_allowHubOpponentInMP", "player_allowHubOpponentInMP", "" },
	{ "player_MGUseRadius", "5403", "" },
	{ "player_throwbackInnerRadius", "2729", "" },
	{ "player_throwbackOuterRadius", "2657", "" },
	{ "player_useRadius", "2098", "" },
	{ "playercard_cache_download_max_retry_time", "301", "" },
	{ "playercard_cache_download_retry_step", "3347", "" },
	{ "playercard_cache_upload_max_retry_time", "3644", "" },
	{ "playercard_cache_upload_retry_step", "2476", "" },
	{ "playercard_cache_validity_life", "5175", "" },
	{ "playercard_fetch_own_enabled", "playercard_fetch_own_enabled", "" },
	{ "playlist_image", "1676", "" },
	{ "playlist_name", "playlist_name", "" },
	{ "playlistAggrFilename", "1415", "" },
	{ "playlistFilename", "1396", "" },
	{ "playListUpdateCheckMinutes", "1580", "" },
	{ "prelaunchdemo", "1258", "" },
	{ "r_adapter", "r_adapter", "" },
	{ "r_airLightBlendTime", "4013", "" },
	{ "r_airLightForceHQ", "1432", "" },
	{ "r_airLightForceLQ", "2697", "" },
	{ "r_airLightScoreMinimum", "2258", "" },
	{ "r_airLightScoreRadiusPower", "564", "" },
	{ "r_airLightUpsampleDepthMaximum", "1355", "" },
	{ "r_airLightUpsampleDepthThresholdAngle", "4688", "" },
	{ "r_airLightVertexInnerMutedRadius", "2981", "" },
	{ "r_allowHDR", "r_allowHDR", "" },
	{ "r_animatedVertsNoCacheScale", "3220", "" },
	{ "r_animatedVertsUseNoCacheLimit", "2274", "" },
	{ "r_aoBlurSharpness", "609", "" },
	{ "r_aoBlurStep", "3283", "" },
	{ "r_aoDiminish", "5848", "" },
	{ "r_aoPower", "3888", "" },
	{ "r_aoStrength", "3697", "" },
	{ "r_aoUseTweaks", "5618", "" },
	{ "r_artUseTweaks", "5960", "" },
	{ "r_aspectRatio", "r_aspectRatio", "" },
	{ "r_atlasAnimFPS", "1289", "" },
	{ "r_balanceLightmapOpaqueLists", "2599", "Split lightmap opaque into multiple draw lists." },
	{ "r_blacklevel", "r_blacklevel", "" },
	{ "r_blur", "797", "Dev tweak to blur the screen" },
	{ "r_blurdstGaussianBlurLevel", "3261", "MIP level to start gaussian blur at" },
	{ "r_blurdstGaussianBlurRadius", "190", "Amount to gaussian blur blur distortion render target" },
	{ "r_brightness", "1691", "Brightness adjustment" },
	{ "r_cacheModelLighting", "4636", "" },
	{ "r_characterSceneEnable", "5475", "" },
	{ "r_chromaticAberration", "3588", "" },
	{ "r_chromaticAberrationAlpha", "700", "" },
	{ "r_chromaticAberrationTweaks", "4946", "" },
	{ "r_chromaticPostOpaqueFX", "2083", "" },
	{ "r_chromaticSeparationB", "2185", "" },
	{ "r_chromaticSeparationG", "1816", "" },
	{ "r_chromaticSeparationR", "4160", "" },
	{ "r_clear", "4996", "Controls how the color buffer is cleared" },
	{ "r_clearColor", "5157", "" },
	{ "r_clearColor2", "4318", "" },
	{ "r_clutCompositeVisionSet", "855", "" },
	{ "r_colorGradingEnable", "523", "" },
	{ "r_colorimetryHDRDisableBlackLevelAdjust", "4268", "" },
	{ "r_colorimetryHDRExposureAdjust", "2268", "" },
	{ "r_colorimetryHDRForcePQ", "5322", "" },
	{ "r_colorimetrySDRForcePQ", "5246", "" },
	{ "r_colorMap", "3391", "Replace all color maps with pure black or pure white" },
	{ "r_daltonizeIntensity", "r_daltonizeIntensity", "" },
	{ "r_daltonizeMode", "r_daltonizeMode", "" },
	{ "r_defaultPatchCount", "3923", "Patches per thread group for all other surfaces." },
	{ "r_delayAddSceneModels", "3337", "" },
	{ "r_depthHackPrepass", "1342", "" },
	{ "r_depthPrepass", "4600", "" },
	{ "r_depthSortEnable", "1114", "" },
	{ "r_depthSortRange", "1414", "" },
	{ "r_desaturation", "1821", "Desaturation adjustment" },
	{ "r_detailMap", "2194", "Replace all detail maps with an image that effectively disables them" },
	{ "r_displacementMap", "4388", "Replace all displacement maps with an image that effectively disables them" },
	{ "r_displacementPatchCount", "3287", "Patches per thread group for displacement surfaces." },
	{ "r_distortion", "5094", "Enable distortion" },
	{ "r_distortion_script_force_off", "922", "Force distortion off in script" },
	{ "r_dof_bias", "97", "" },
	{ "r_dof_enable", "2046", "" },
	{ "r_dof_farBlur", "1256", "" },
	{ "r_dof_farEnd", "4058", "" },
	{ "r_dof_farStart", "756", "" },
	{ "r_dof_limit", "r_dof_limit", "" },
	{ "r_dof_nearBlur", "2208", "" },
	{ "r_dof_nearEnd", "2580", "" },
	{ "r_dof_nearStart", "875", "" },
	{ "r_dof_physical_adsFocusSpeed", "4854", "" },
	{ "r_dof_physical_adsMaxFstop", "1315", "" },
	{ "r_dof_physical_adsMinFstop", "4242", "" },
	{ "r_dof_physical_filmDiagonal", "4419", "" },
	{ "r_dof_physical_focusDistance", "1920", "" },
	{ "r_dof_physical_fstop", "3380", "" },
	{ "r_dof_physical_hipEnable", "1972", "" },
	{ "r_dof_physical_hipFstop", "2186", "" },
	{ "r_dof_physical_hipSharpCocDiameter", "275", "" },
	{ "r_dof_physical_maxCocDiameter", "2888", "" },
	{ "r_dof_physical_minFocusDistance", "2386", "" },
	{ "r_dof_physical_viewModelFocusDistance", "1052", "" },
	{ "r_dof_physical_viewModelFstop", "1077", "" },
	{ "r_dof_physicalHipFocusSpeed", "5398", "" },
	{ "r_dof_tweak", "2", "" },
	{ "r_dof_viewModelEnd", "5414", "" },
	{ "r_dof_viewModelStart", "231", "" },
	{ "r_drawSun", "2850", "Enable sun effects" },
	{ "r_dynamicSpotLightShadows", "4739", "" },
	{ "r_elevatedPriority", "r_elevatedPriority", "" },
	{ "r_emblemBrightnessScale", "2735", "" },
	{ "r_emissiveMap", "769", "Replace all emissive maps with pure black or pure white" },
	{ "r_envBrdfLutMap", "3818", "Replace environment BRDF lookup table with pure black (no secondary specular) or pure white (maximum secondary specular)" },
	{ "r_eyeHighlightColor", "5421", "" },
	{ "r_eyeHighlightIntensity", "4065", "" },
	{ "r_eyePupil", "1932", "" },
	{ "r_eyeRedness", "3458", "" },
	{ "r_eyeRednessVeins", "1845", "" },
	{ "r_eyeSparkle", "727", "" },
	{ "r_filmGrainFps", "3289", "" },
	{ "r_filmGrainIntensity", "4276", "" },
	{ "r_filmGrainUseTweaks", "4316", "" },
	{ "r_filmTweakBrightness", "2750", "Tweak dev var; film color brightness" },
	{ "r_filmTweakContrast", "2440", "Tweak dev var; film color contrast" },
	{ "r_filmTweakDarkTint", "1760", "Tweak dev var; film color dark tint color" },
	{ "r_filmTweakDesaturation", "3859", "Tweak dev var; Desaturation applied after all 3D drawing to light" },
	{ "r_filmTweakDesaturationDark", "724", "Tweak dev var; Additional desaturation applied after all 3D drawing to dark areas" },
	{ "r_filmTweakEnable", "3114", "Tweak dev var; enable film color effects" },
	{ "r_filmTweakIntensity", "3025", "Tweak dev var; film color intensity" },
	{ "r_filmTweakInvert", "3026", "Tweak dev var; enable inverted video" },
	{ "r_filmTweakLightTint", "4601", "Tweak dev var; film color light tint color" },
	{ "r_filmTweakMediumTint", "905", "Tweak dev var; film color medium tint color" },
	{ "r_fog_depthhack_scale", "645", "Fog scale for depth hack surfaces" },
	{ "r_fogScale", "5051", "" },
	{ "r_fogScaleEnable", "5217", "" },
	{ "r_foliageWindMaterialParams", "842", "" },
	{ "r_forceLod", "3361", "" },
	{ "r_forwardPlusMode", "5818", "" },
	{ "r_frustomLightUseZBinning", "2244", "" },
	{ "r_frustumLightProxyConsExpand", "3675", "" },
	{ "r_frustumLightProxyExpand", "2893", "" },
	{ "r_frustumLightProxyMargin", "2922", "" },
	{ "r_frustumLightProxyUseMeshCheck", "3579", "" },
	{ "r_fullscreen", "r_fullscreen", "" },
	{ "r_fullscreenWindow", "r_fullscreenWindow", "" },
	{ "r_fullscreenWindowExtend", "r_fullscreenWindowExtend", "" },
	{ "r_fullscreenWindowExtendMode", "r_fullscreenWindowExtendMode", "" },
	{ "r_fxaaSubpixel", "1917", "" },
	{ "r_globalGenericMaterialScale", "2807", "Hack global generic material constants" },
	{ "r_globalSecondarySelfVisLerpToFullyOpen", "5139", "" },
	{ "r_globalSecondarySelfVisScale", "1264", "" },
	{ "r_gtaoQualityLevel", "5156", "" },
	{ "r_hdrBlackPointLevel", "r_hdrBlackPointLevel", "" },
	{ "r_hdrGammaCurveLevel", "r_hdrGammaCurveLevel", "" },
	{ "r_hdrWhitePointLevel", "r_hdrWhitePointLevel", "" },
	{ "r_hemiAoBlurTolerance", "2117", "" },
	{ "r_hemiAoCombineResolutionsBeforeBlur", "465", "" },
	{ "r_hemiAoCombineResolutionsWithMul", "3011", "" },
	{ "r_hemiAoDepthSquash", "2843", "" },
	{ "r_hemiAoHierarchyDepth", "5329", "" },
	{ "r_hemiAoMaxDepthDownsample", "2983", "" },
	{ "r_hemiAoNoiseFilterTolerance", "487", "" },
	{ "r_hemiAoPower", "3869", "" },
	{ "r_hemiAoQualityLevel", "1044", "" },
	{ "r_hemiAoRejectionFalloff", "4830", "" },
	{ "r_hemiAoStrength", "554", "Strength of Hemi Screen Space Ambient Occlusion effect" },
	{ "r_hemiAoUpsampleTolerance", "2689", "" },
	{ "r_hudFx", "4475", "" },
	{ "r_hudOutlineAlpha0", "31", "" },
	{ "r_hudOutlineAlpha0Broadcaster", "5531", "" },
	{ "r_hudOutlineAlpha1", "1070", "" },
	{ "r_hudOutlineAlpha1Broadcaster", "978", "" },
	{ "r_hudOutlineCloakBlurRadius", "2530", "" },
	{ "r_hudOutlineCloakDarkenScale", "4701", "" },
	{ "r_hudOutlineCloakLumScale", "2362", "" },
	{ "r_hudOutlineCloakWhen", "1018", "" },
	{ "r_hudOutlineCurvyBlurRadius", "1486", "" },
	{ "r_hudOutlineCurvyDarkenScale", "4501", "" },
	{ "r_hudOutlineCurvyDepth", "4008", "" },
	{ "r_hudOutlineCurvyLumScale", "961", "" },
	{ "r_hudOutlineCurvyWhen", "3187", "" },
	{ "r_hudOutlineCurvyWidth", "710", "" },
	{ "r_hudOutlineEnable", "2976", "" },
	{ "r_hudOutlineHaloBlurRadius", "2197", "" },
	{ "r_hudOutlineHaloDarkenScale", "726", "" },
	{ "r_hudOutlineHaloLumScale", "1173", "" },
	{ "r_hudOutlineHaloWhen", "593", "" },
	{ "r_hudOutlinePostMode", "1394", "" },
	{ "r_hudOutlineWhen", "2903", "" },
	{ "r_hudOutlineWidth", "5539", "" },
	{ "r_hudOutlineWidthBroadcaster", "3248", "" },
	{ "r_ignore", "4481", "used for debugging anything (stripped)" },
	{ "r_ignoref", "5207", "" },
	{ "r_imageQuality", "r_imageQuality", "" },
	{ "r_keepSunShadowCache", "1708", "" },
	{ "r_keyLightAlliesCharColor", "5018", "" },
	{ "r_keyLightAxisCharColor", "1937", "" },
	{ "r_keyLightDirection", "3142", "" },
	{ "r_keyLightDistanceMax", "1603", "" },
	{ "r_keyLightDistanceMin", "1878", "" },
	{ "r_keyLightSpecScale", "4409", "" },
	{ "r_keyLightStrength", "2910", "" },
	{ "r_lateAllocParamCacheAllowed", "1518", "" },
	{ "r_lightDpvs", "3825", "" },
	{ "r_lightGridDefaultFXLightingLookup", "1307", "Default FX lighting lookup location" },
	{ "r_lightGridDefaultModelLightingLookup", "3460", "Default model lighting lookup location" },
	{ "r_lightGridTempSmoothingFactor", "2677", "" },
	{ "r_lightMap", "3271", "Replace all lightmaps with pure black or pure white" },
	{ "r_litSurfaceHDRScalar", "1097", "Vision set based scalar applied to lit surfaces" },
	{ "r_loadForRenderer", "4838", "Set to false to disable dx allocations (for dedicated server mode)" },
	{ "r_lockPvs", "1897", "" },
	{ "r_lodBiasRigid", "r_lodBiasRigid", "" },
	{ "r_lodBiasSkinned", "r_lodBiasSkinned", "" },
	{ "r_lodDynamicScale", "1111", "" },
	{ "r_lodScaleRigid", "r_lodScaleRigid", "" },
	{ "r_lodScaleSkinned", "r_lodScaleSkinned", "" },
	{ "r_materialLod0SizeThreshold", "1099", "" },
	{ "r_materialLodMin", "3389", "" },
	{ "r_materialLodOverride", "5148", "" },
	{ "r_materialWind", "1520", "" },
	{ "r_maxScreenSpaceShadowsSamplesTotal", "4241", "" },
	{ "r_mbCameraRotationInfluence", "5469", "" },
	{ "r_mbCameraTranslationInfluence", "904", "" },
	{ "r_mbEnable", "712", "" },
	{ "r_mbLimit", "r_mbLimit", "" },
	{ "r_mbPreset", "240", "" },
	{ "r_mbVelocityScalar", "4947", "" },
	{ "r_mdao", "5153", "" },
	{ "r_mdaoAsyncOccluderGen", "449", "" },
	{ "r_mdaoBoneInfluenceRadiusScale", "4330", "" },
	{ "r_mdaoCapsuleStrength", "5085", "" },
	{ "r_mdaoLimit", "r_mdaoLimit", "" },
	{ "r_mdaoMinBoneBoundsToOcclude", "2499", "" },
	{ "r_mdaoOccluderCullDistance", "489", "" },
	{ "r_mdaoOccluderFadeOutStartDistance", "661", "" },
	{ "r_mdaoUseTweaks", "2038", "" },
	{ "r_mdaoVolumeStrength", "1988", "" },
	{ "r_minScreenSpaceShadowsSamplesPerLight", "4941", "" },
	{ "r_mode", "r_mode", "" },
	{ "r_monitor", "r_monitor", "" },
	{ "r_mpRimColor", "2013", "Change character's rim color for multiplayer" },
	{ "r_mpRimDiffuseTint", "817", "Change character's rim diffuse tint for multiplayer." },
	{ "r_mpRimStrength", "2634", "Change character's rim strength for multiplayer" },
	{ "r_normalMap", "5467", "Replace all normal maps with a flat normal map" },
	{ "r_offchipTessellationAllowed", "1938", "" },
	{ "r_offchipTessellationTfThreshold", "635", "" },
	{ "r_offchipTessellationWaveThreshold", "4679", "" },
	{ "r_outdoorFeather", "161", "Outdoor z-feathering value" },
	{ "r_patchCountAllowed", "3925", "Enable run-time setting of patch count per draw call." },
	{ "r_picmip", "r_picmip", "" },
	{ "r_picmip_bump", "r_picmip_bump", "" },
	{ "r_picmip_spec", "r_picmip_spec", "" },
	{ "r_polygonOffsetScale", "3557", "Offset scale for decal polygons; bigger values z-fight less but poke through walls more" },
	{ "r_portalBevels", "5317", "" },
	{ "r_portalBevelsOnly", "3948", "" },
	{ "r_portalMinClipArea", "634", "Don't clip child portals by a parent portal smaller than this fraction of the screen area." },
	{ "r_portalMinRecurseDepth", "3100", "Ignore r_portalMinClipArea for portals with fewer than this many parent portals." },
	{ "r_portalWalkLimit", "2909", "" },
	{ "r_postAAMode", "r_postAAMode", "" },
	{ "r_postfx_enable", "5605", "" },
	{ "r_preBakedTndTweaks", "297", "" },
	{ "r_preloadShaders", "r_preloadShaders", "" },
	{ "r_preloadShadersELL", "r_preloadShadersELL", "" },
	{ "r_preloadShadersELLMSPT", "r_preloadShadersELLMSPT", "" },
	{ "r_preloadShadersWNDTOO", "r_preloadShadersWNDTOO", "" },
	{ "r_refreshRate", "r_refreshRate", "" },
	{ "r_rimLightBias", "5332", "" },
	{ "r_rimLightFalloffMaxDistance", "5574", "" },
	{ "r_rimLightFalloffMinDistance", "915", "" },
	{ "r_rimLightFarEdgeSharpness", "2403", "" },
	{ "r_rimLightIntensity", "5482", "" },
	{ "r_rimLightNearEdgeSharpness", "2315", "" },
	{ "r_rimLightShadowBrightening", "3816", "" },
	{ "r_rimLightSharpnessDistance", "1079", "" },
	{ "r_rimLightUseTweaks", "4267", "" },
	{ "r_sceneMipShowOverlay", "802", "" },
	{ "r_screenSpaceShadows", "4712", "" },
	{ "r_screenSpaceShadowsForce", "r_screenSpaceShadowsForce", "" },
	{ "r_showModelLightingLowWaterMark", "3116", "" },
	{ "r_skipPvs", "2745", "" },
	{ "r_skyResolution", "r_skyResolution", "" },
	{ "r_smaaCompute", "259", "" },
	{ "r_smaaFilmicStrength", "3545", "" },
	{ "r_smaaTemporalGradientAdjust", "1444", "" },
	{ "r_smaaTemporalQuincunx", "205", "" },
	{ "r_smaaTemporalUpsampleMode", "2699", "" },
	{ "r_smaaTemporalUpsamplePercent", "r_smaaTemporalUpsamplePercent", "" },
	{ "r_specOccMap", "5620", "Replace all specular occlusion maps with pure black (fully occluded) or pure white (not occluded)" },
	{ "r_specularMap", "2427", "Replace all specular maps with pure black (off) or pure white (super shiny)" },
	{ "r_ssao", "1578", "" },
	{ "r_ssaoDebug", "1617", "" },
	{ "r_ssaoDebugMip", "497", "" },
	{ "r_ssaoDepthScale", "1870", "" },
	{ "r_ssaoDepthScaleViewModel", "2358", "" },
	{ "r_ssaoDownsample", "4469", "" },
	{ "r_ssaoFadeDepth", "3404", "" },
	{ "r_ssaoGapFalloff", "1869", "" },
	{ "r_ssaoGradientFalloff", "4816", "" },
	{ "r_ssaoLimit", "r_ssaoLimit", "" },
	{ "r_ssaoMaxStrengthDepth", "2937", "Depth at which SSAO strength is at its maximum" },
	{ "r_ssaoMinPixelWidth", "225", "" },
	{ "r_ssaoMinStrengthDepth", "3315", "Depth at which SSAO strength is zero, effectively disabled" },
	{ "r_ssaoMultiRes", "1081", "" },
	{ "r_ssaoPower", "3537", "" },
	{ "r_ssaoRejectDepth", "626", "" },
	{ "r_ssaoSampleCount", "1678", "" },
	{ "r_ssaoScriptScale", "212", "" },
	{ "r_ssaoStrength", "4361", "" },
	{ "r_ssaoUseTweaks", "4822", "" },
	{ "r_ssaoWidth", "919", "" },
	{ "r_ssrEnabled", "r_ssrEnabled", "" },
	{ "r_ssrMaxQuality", "r_ssrMaxQuality", "" },
	{ "r_ssrPositionCorrection", "4924", "" },
	{ "r_ssrQualityLevel", "r_ssrQualityLevel", "" },
	{ "r_sssEnable", "2954", "" },
	{ "r_sssFarScatteringRadius", "4310", "" },
	{ "r_sssFarToNearBlend", "4099", "" },
	{ "r_sssGlobalRadius", "4172", "" },
	{ "r_sssLimit", "r_sssLimit", "" },
	{ "r_sssNearScatteringRadius", "439", "" },
	{ "r_sssPreset", "3760", "" },
	{ "r_subdivPatchCount", "4902", "Patches per thread group for sub-division surfaces." },
	{ "r_subwindow", "4019", "" },
	{ "r_sun_from_dvars", "2255", "" },
	{ "r_sun_fx_position", "3196", "" },
	{ "r_sunblind_fadein", "4939", "" },
	{ "r_sunblind_fadeout", "407", "" },
	{ "r_sunblind_max_angle", "3858", "" },
	{ "r_sunblind_max_darken", "1590", "" },
	{ "r_sunblind_min_angle", "5397", "" },
	{ "r_sunflare_fadein", "371", "" },
	{ "r_sunflare_fadeout", "1615", "" },
	{ "r_sunflare_max_alpha", "2957", "" },
	{ "r_sunflare_max_angle", "3627", "" },
	{ "r_sunflare_max_size", "89", "" },
	{ "r_sunflare_min_angle", "1834", "" },
	{ "r_sunflare_min_size", "2938", "" },
	{ "r_sunflare_shader", "5654", "name for flare effect; can be any material" },
	{ "r_sunglare_fadein", "3538", "" },
	{ "r_sunglare_fadeout", "438", "" },
	{ "r_sunglare_max_angle", "970", "" },
	{ "r_sunglare_max_lighten", "4772", "" },
	{ "r_sunglare_min_angle", "3682", "" },
	{ "r_sunInfDist", "3273", "" },
	{ "r_sunPostDrawBeforeTrans", "849", "" },
	{ "r_sunshadowmap_cmdbuf_worker", "5260", "Process shadowmap command buffer in a separate thread" },
	{ "r_sunsprite_shader", "4843", "name for static sprite; can be any material" },
	{ "r_sunsprite_size", "4337", "" },
	{ "r_temporalSamplingEnable", "1295", "" },
	{ "r_tessellationEyeScale", "330", "" },
	{ "r_tessellationHeightAuto", "75", "" },
	{ "r_tessellationHeightScale", "672", "" },
	{ "r_tessellationHybrid", "551", "" },
	{ "r_texFilterAnisoMax", "r_texFilterAnisoMax", "" },
	{ "r_texFilterAnisoMin", "r_texFilterAnisoMin", "" },
	{ "r_texFilterDisable", "91", "Disables all texture filtering (uses nearest only.)" },
	{ "r_texFilterMipBias", "3569", "Change the mipmap bias" },
	{ "r_texFilterMipMode", "4107", "Forces all mipmaps to use a particular blend between levels (or disables mipping.)" },
	{ "r_texFilterProbeBilinear", "5634", "Force reflection probe to use bilinear filter" },
	{ "r_texShowMipMode", "2416", "Forces textures with the specified mip filtering to draw black." },
	{ "r_tonemap", "3717", "HDR Tonemapping mode" },
	{ "r_tonemapAdaptSpeed", "810", "" },
	{ "r_tonemapAuto", "4119", "HDR Tonemapping performs auto-exposure" },
	{ "r_tonemapAutoExposureAdjust", "4568", "" },
	{ "r_tonemapBlack", "5761", "" },
	{ "r_tonemapBlend", "491", "HDR Tonemapping blends between exposures" },
	{ "r_tonemapCrossover", "3201", "" },
	{ "r_tonemapDarkEv", "162", "" },
	{ "r_tonemapDarkExposureAdjust", "3613", "" },
	{ "r_tonemapExposure", "5385", "" },
	{ "r_tonemapExposureAdjust", "1035", "" },
	{ "r_tonemapLightEv", "4694", "" },
	{ "r_tonemapLightExposureAdjust", "2679", "" },
	{ "r_tonemapLockAutoExposureAdjust", "2442", "HDR Tonemapping lock auto exposure adjust" },
	{ "r_tonemapMaxExposure", "1326", "" },
	{ "r_tonemapMaxExposureAdjust", "4961", "" },
	{ "r_tonemapMidEv", "3799", "" },
	{ "r_tonemapMidExposureAdjust", "1648", "" },
	{ "r_tonemapMinExposureAdjust", "5773", "" },
	{ "r_tonemapShoulder", "2821", "" },
	{ "r_tonemapToe", "2788", "" },
	{ "r_tonemapUseCS", "338", "" },
	{ "r_tonemapUseTweaks", "1514", "Override tone map LightSet settings with tweak dvar values." },
	{ "r_tonemapWhite", "3250", "" },
	{ "r_uiBlurDstMode", "1175", "UI blur distortion mode. Fast uses the scene mip map render target, PostSun uses a downsampled post sun resolve buffer, PostSun HQ uses a gaussian blurred post sun resolve buffer." },
	{ "r_unlitSurfaceHDRScalar", "284", "Vision set based scalar applied to unlit surfaces to balance those surfaces with the luminance of the scene" },
	{ "r_useAerialLod", "1841", "" },
	{ "r_useLightGridDefaultFXLightingLookup", "1074", "Enable/disable default fx lighting lookup" },
	{ "r_useLightGridDefaultModelLightingLookup", "2706", "Enable/disable default model lighting lookup" },
	{ "r_useShadowGeomOpt", "4163", "Enable iwRad shadow geometry optimization. It only works when we have the data generated in iwRad." },
	{ "r_veil", "1133", "Apply veiling luminance (HDR glow)" },
	{ "r_veilAntialiasing", "5340", "" },
	{ "r_veilBackgroundStrength", "2219", "" },
	{ "r_veilFalloffScale1", "1538", "" },
	{ "r_veilFalloffScale2", "3060", "" },
	{ "r_veilFalloffWeight1", "4397", "" },
	{ "r_veilFalloffWeight2", "3548", "" },
	{ "r_veilFilter", "22", "" },
	{ "r_veilPreset", "3810", "" },
	{ "r_veilRadius", "4456", "" },
	{ "r_veilStrength", "5621", "" },
	{ "r_veilUseTweaks", "2707", "Override veil LightSet settings with tweak dvar values." },
	{ "r_velocityPrepass", "237", "" },
	{ "r_velocityPrepassDepthHack", "807", "" },
	{ "r_videoMemoryScale", "r_videoMemoryScale", "" },
	{ "r_volumeLightScatter", "2696", "Enables volumetric light scattering" },
	{ "r_volumeLightScatterAngularAtten", "750", "" },
	{ "r_volumeLightScatterBackgroundDistance", "4506", "" },
	{ "r_volumeLightScatterColor", "3200", "" },
	{ "r_volumeLightScatterDepthAttenFar", "5444", "" },
	{ "r_volumeLightScatterDepthAttenNear", "3070", "" },
	{ "r_volumeLightScatterEv", "4638", "" },
	{ "r_volumeLightScatterLinearAtten", "2564", "" },
	{ "r_volumeLightScatterQuadraticAtten", "3758", "" },
	{ "r_volumeLightScatterUseTweaks", "3889", "" },
	{ "r_volumetricDepth", "3395", "" },
	{ "r_vramOverheadFraction", "r_vramOverheadFraction", "" },
	{ "r_vsync", "r_vsync", "" },
	{ "r_warningRepeatDelay", "1371", "" },
	{ "r_windowExtendFit", "r_windowExtendFit", "" },
	{ "r_zfar", "484", "Change the distance at which culling fog reaches 100% opacity; 0 is off" },
	{ "r_znear", "3153", "" },
	{ "radarjamDistMax", "4545", "" },
	{ "radarjamDistMin", "5504", "" },
	{ "radarjamSinCurve", "4632", "" },
	{ "ragdoll_enable", "ragdoll_enable", "" },
	{ "ragdoll_mp_limit", "ragdoll_mp_limit", "" },
	{ "rankedLockoutStrikeCooldown", "5754", "" },
	{ "rankedPlayDisableFourPlayer", "rankedPlayDisableFourPlayer", "" },
	{ "rankedPlayInitialMMR", "2203", "" },
	{ "rankedPlayInitialWeight", "1833", "" },
	{ "rankedPlayLeavePenaltyMasks", "rankedPlayLeavePenaltyMasks", "" },
	{ "rankedPlayLockoutDuration", "12", "" },
	{ "rankedPlayLockoutMaxStrikes", "852", "" },
	{ "rankedPlayMinimumMatchAdjustmentThreshold", "rankedPlayMinimumMatchAdjustmentThreshold", "" },
	{ "rankedPlayPlacementSeasons", "rankedPlayPlacementSeasons", "" },
	{ "rankedPlaySeasonTransformMaxMMR", "rankedPlaySeasonTransformMaxMMR", "" },
	{ "rankedPlayUseClientAlgorithm", "rankedPlayUseClientAlgorithm", "" },
	{ "rankedPlayUseClientTransitionAlgorithm", "rankedPlayUseClientTransitionAlgorithm", "" },
	{ "rankedPlayUseEngineCommit", "rankedPlayUseEngineCommit", "" },
	{ "restrictMapPacksToGroups", "2764", "" },
	{ "riotshield_deploy_trace_parallel", "4101", "" },
	{ "riotshield_deployed_health", "650", "" },
	{ "safeArea_adjusted_horizontal", "245", "" },
	{ "safeArea_adjusted_vertical", "4227", "" },
	{ "safeArea_horizontal", "4914", "" },
	{ "safeArea_vertical", "5775", "" },
	{ "scr_diehard", "scr_diehard", "" },
	{ "scr_enable_flybywire", "scr_enable_flybywire", "" },
	{ "scr_game_allowkillcam", "scr_game_allowkillcam", "" },
	{ "scr_game_compassRadarUpdateTime", "scr_game_compassRadarUpdateTime", "" },
	{ "scr_game_deathpointloss", "scr_game_deathpointloss", "" },
	{ "scr_game_forceuav", "scr_game_forceuav", "" },
	{ "scr_game_graceperiod", "scr_game_graceperiod", "" },
	{ "scr_game_hardpoints", "scr_game_hardpoints", "" },
	{ "scr_game_killstreakdelay", "scr_game_killstreakdelay", "" },
	{ "scr_game_lockspectatorpov", "scr_game_lockspectatorpov", "" },
	{ "scr_game_matchstarttime", "scr_game_matchstarttime", "" },
	{ "scr_game_minimapHiddenWhileADS", "scr_game_minimapHiddenWhileADS", "" },
	{ "scr_game_onlyheadshots", "scr_game_onlyheadshots", "" },
	{ "scr_game_perks", "scr_game_perks", "" },
	{ "scr_game_playerwaittime", "scr_game_playerwaittime", "" },
	{ "scr_game_radarMode", "scr_game_radarMode", "" },
	{ "scr_game_roundstarttime", "scr_game_roundstarttime", "" },
	{ "scr_game_spectatetype", "scr_game_spectatetype", "" },
	{ "scr_game_suicidepointloss", "scr_game_suicidepointloss", "" },
	{ "scr_game_suicidespawndelay", "scr_game_suicidespawndelay", "" },
	{ "scr_hardcore", "scr_hardcore", "" },
	{ "scr_hardcore_StreaksTeamKill", "scr_hardcore_StreaksTeamKill", "" },
	{ "scr_hardpoint_allowartillery", "scr_hardpoint_allowartillery", "" },
	{ "scr_hardpoint_allowhelicopter", "scr_hardpoint_allowhelicopter", "" },
	{ "scr_hardpoint_allowuav", "scr_hardpoint_allowuav", "" },
	{ "scr_oldschool", "scr_oldschool", "" },
	{ "scr_oneShot", "scr_oneShot", "" },
	{ "scr_player_forcerespawn", "scr_player_forcerespawn", "" },
	{ "scr_player_healthregentime", "scr_player_healthregentime", "" },
	{ "scr_player_maxhealth", "scr_player_maxhealth", "" },
	{ "scr_player_numlives", "scr_player_numlives", "" },
	{ "scr_player_respawndelay", "scr_player_respawndelay", "" },
	{ "scr_player_sprinttime", "scr_player_sprinttime", "" },
	{ "scr_player_suicidespawndelay", "scr_player_suicidespawndelay", "" },
	{ "scr_team_fftype", "scr_team_fftype", "" },
	{ "scr_team_respawntime", "scr_team_respawntime", "" },
	{ "scr_team_teamkillkicklimit", "scr_team_teamkillkicklimit", "" },
	{ "scr_team_teamkillpointloss", "scr_team_teamkillpointloss", "" },
	{ "scr_team_teamkillspawndelay", "scr_team_teamkillspawndelay", "" },
	{ "scr_thirdPerson", "scr_thirdPerson", "" },
	{ "scr_wanderlustOnly", "scr_wanderlustOnly", "" },
	{ "shadowplay_highlights_enabled", "shadowplay_highlights_enabled", "" },
	{ "shadowplay_killcam_highlights_enabled", "shadowplay_killcam_highlights_enabled", "" },
	{ "shadowplay_killswitch", "shadowplay_killswitch", "" },
	{ "showPlaylistTotalPlayers", "5293", "" },
	{ "sm_cacheSpotShadows", "sm_cacheSpotShadows", "" },
	{ "sm_cacheSunShadow", "sm_cacheSunShadow", "" },
	{ "sm_debugFastSunShadow", "4583", "Debug fast sun shadow" },
	{ "sm_dynlightAllSModels", "5657", "" },
	{ "sm_enable", "sm_enable", "" },
	{ "sm_fastSunShadow", "4583", "Fast sun shadow" },
	{ "sm_minSpotLightScore", "5176", "Minimum score (based on intensity, radius, and position relative to the camera) for a spot light to have shadow maps." },
	{ "sm_roundRobinPrioritySpotShadows", "3942", "" },
	{ "sm_shadowUseTweaks", "657", "Override shadow LightSet settings with tweak dvar values." },
	{ "sm_spotDistCull", "1875", "Distance cull spot shadows" },
	{ "sm_spotEnable", "2030", "" },
	{ "sm_spotFilterRadius", "3546", "" },
	{ "sm_spotLightScoreModelScale", "4230", "Scale the calculated spot light score by this value if the light currently only affects static or script brush models." },
	{ "sm_spotLightScoreRadiusPower", "1475", "" },
	{ "sm_spotPolygonOffsetBias", "3357", "" },
	{ "sm_spotPolygonOffsetClamp", "136", "" },
	{ "sm_spotPolygonOffsetScale", "4087", "" },
	{ "sm_spotShadowBitDepth", "sm_spotShadowBitDepth", "" },
	{ "sm_spotShadowFadeTime", "3286", "How many seconds it takes for a primary light shadow map to fade in or out" },
	{ "sm_spotShadowMapSize", "935", "" },
	{ "sm_spotUpdateLimit", "2225", "" },
	{ "sm_strictCull", "4889", "Strict shadow map cull" },
	{ "sm_sunEnable", "1084", "Enable sun shadow mapping from script" },
	{ "sm_sunFilterRadius", "3299", "" },
	{ "sm_sunPolygonOffsetBias", "5142", "" },
	{ "sm_sunPolygonOffsetClamp", "3266", "" },
	{ "sm_sunPolygonOffsetScale", "2428", "" },
	{ "sm_sunSampleSizeNear", "5699", "" },
	{ "sm_sunShadowBitDepth", "sm_sunShadowBitDepth", "" },
	{ "sm_sunShadowBoundsMax", "419", "" },
	{ "sm_sunShadowBoundsMin", "2611", "" },
	{ "sm_sunShadowBoundsOverride", "1064", "" },
	{ "sm_sunShadowCenter", "450", "" },
	{ "sm_sunShadowCenterMode", "775", "" },
	{ "sm_sunShadowScale", "3158", "" },
	{ "sm_tileResolution", "sm_tileResolution", "" },
	{ "sm_usedSunCascadeCountSceneEnt", "5042", "" },
	{ "snd_announcerDisabled", "3059", "" },
	{ "snd_announcerVoicePrefix", "3", "Local mp announcer voice to use" },
	{ "snd_battlechatterDisabled", "3398", "" },
	{ "snd_detectedSpeakerConfig", "2198", "" },
	{ "snd_enableEq", "1482", "" },
	{ "snd_enableReverb", "2654", "" },
	{ "snd_errorOnMissing", "2321", "" },
	{ "snd_hitsoundDisabled", "1849", "" },
	{ "snd_hitsoundVolume", "3293", "" },
	{ "snd_inheritSecondaryPitchVol", "4394", "" },
	{ "snd_musicDisabled", "1990", "" },
	{ "snd_musicDisabledForCustomSoundtrack", "2757", "" },
	{ "snd_occlusionDelay", "3743", "Minimum delay in (ms) between occlusion updates" },
	{ "snd_occlusionLerpTime", "3536", "Time to lerp to target occlusion lerp when occluded" },
	{ "snd_premixVolume", "2945", "" },
	{ "snd_slaveFadeTime", "956", "The amount of time in milliseconds for a 'slave' sound to fade its volumes when a master sound starts or stops" },
	{ "snd_speakerConfig", "2489", "" },
	{ "snd_volume", "5763", "" },
	{ "spawndata_active", "1745", "" },
	{ "spawndata_maxcompressionbuffer", "2149", "" },
	{ "spawning_revised_capturetheflag", "spawning_revised_capturetheflag", "" },
	{ "spawning_revised_cornersighttraces", "spawning_revised_cornersighttraces", "" },
	{ "spawning_revised_domination", "spawning_revised_domination", "" },
	{ "spawning_revised_fatique", "spawning_revised_fatique", "" },
	{ "spawning_revised_frontline", "spawning_revised_frontline", "" },
	{ "spawning_revised_hardpoint", "spawning_revised_hardpoint", "" },
	{ "spawning_revised_teamdeathmatch", "spawning_revised_teamdeathmatch", "" },
	{ "spawning_use_classic", "spawning_use_classic", "" },
	{ "splitscreenMode", "splitscreenMode", "" },
	{ "spv_commandoTacInsert_disabled", "spv_commandoTacInsert_disabled", "" },
	{ "spv_ground_war_active", "spv_ground_war_active", "" },
	{ "spv_hub_firingrange_kswitch", "spv_hub_firingrange_kswitch", "" },
	{ "spv_sku_details_rollout_majority", "spv_sku_details_rollout_majority", "" },
	{ "spv_ui_paintshopInFullHubEnabled", "spv_ui_paintshopInFullHubEnabled", "" },
	{ "sv_blacklistReasons", "sv_blacklistReasons", "" },
	{ "sv_clientPacketsBurstMinCount", "2044", "" },
	{ "sv_maxclients", "2299", "Maximum number of clients on the server" },
	{ "sv_paused", "5351", "Pause the server" },
	{ "sv_running", "1080", "Pause the server" },
	{ "svwp", "765", "playerdata server write protection: 0 = disable, 1 = silent, 2 = kick" },
	{ "tb_report", "3333", "tb event record" },
	{ "team_rebalance", "2451", "rebalance" },
	{ "telemetry_active", "telemetry_active", "" },
	{ "telemetry_error_killswitch", "telemetry_error_killswitch", "" },
	{ "theater_active", "616", "Are we allowed to show theater or not." },
	{ "thermalBlurFactorNoScope", "2346", "" },
	{ "tracer_firstPersonMaxWidth", "886", "" },
	{ "tracer_stoppingPowerColor1", "3726", "" },
	{ "tracer_stoppingPowerColor2", "2658", "" },
	{ "tracer_stoppingPowerColor3", "2410", "" },
	{ "tracer_stoppingPowerColor4", "5169", "" },
	{ "tracer_stoppingPowerColor5", "3870", "" },
	{ "tracer_stoppingPowerOverride", "4844", "" },
	{ "tracer_stoppingPowerWidth", "2824", "" },
	{ "tracer_thermalWidthMult", "4930", "" },
	{ "ui_borderLowLightScale", "5283", "Scales the border color for the lowlight color on certain UI borders" },
	{ "ui_buildLocation", "549", "Where to draw the build number" },
	{ "ui_buildSize", "3759", "" },
	{ "ui_challenge_1_ref", "ui_challenge_1_ref", "" },
	{ "ui_challenge_2_ref", "ui_challenge_2_ref", "" },
	{ "ui_challenge_3_ref", "ui_challenge_3_ref", "" },
	{ "ui_challenge_4_ref", "ui_challenge_4_ref", "" },
	{ "ui_challenge_5_ref", "ui_challenge_5_ref", "" },
	{ "ui_challenge_6_ref", "ui_challenge_6_ref", "" },
	{ "ui_challenge_7_ref", "ui_challenge_7_ref", "" },
	{ "ui_currentFeederMapIndex", "864", "Currently selected map" },
	{ "ui_currentMap", "788", "Current map index" },
	{ "ui_drawCrosshair", "ui_drawCrosshair", "" },
	{ "ui_drawHitmarker", "ui_drawHitmarker", "" },
	{ "ui_force_dont_draw_fighter_names", "ui_force_dont_draw_fighter_names", "" },
	{ "ui_hud_obituaries", "ui_hud_obituaries", "" },
	{ "ui_missingMapName", "2958", "Name of map to show in missing content error" },
	{ "ui_netSource", "1639", "The network source where:   0:Local   1:Internet   2:Favorites" },
	{ "ui_onlineRequired", "3556", "UI requires online connection to be present." },
	{ "ui_partyUpActive", "ui_partyUpActive", "" },
	{ "ui_partyUpDialogRequested", "ui_partyUpDialogRequested", "" },
	{ "ui_partyUpEnabled", "ui_partyUpEnabled", "" },
	{ "ui_promotion", "ui_promotion", "" },
	{ "ui_raid_hide_fighter", "ui_raid_hide_fighter", "" },
	{ "ui_raid_hide_scorestreaks", "ui_raid_hide_scorestreaks", "" },
	{ "ui_selectedFeederMap", "264", "Current preview game type" },
	{ "ui_serverStatusTimeOut", "2382", "Time in milliseconds before a server status request times out" },
	{ "ui_showDLCMaps", "880", "" },
	{ "ui_showPaintshop", "ui_showPaintshop", "Allow paintjobs to be applied to weapons" },
	{ "ui_war_last_obj_flipped", "ui_war_last_obj_flipped", "" },
	{ "useNewVL", "4476", "" },
	{ "UsePickTen", "683", "" },
	{ "useRelativeTeamColors", "1244", "" },
	{ "userGroup_active", "1021", "Are we allowed to show Usergroups or not" },
	{ "userGroup_cool_off_time", "776", "" },
	{ "userGroup_max_retry_time", "1490", "" },
	{ "userGroup_refresh_time_secs", "55", "" },
	{ "userGroup_retry_step", "1419", "" },
	{ "userGroup_RetryTime", "227", "" },
	{ "validate_playtime_enabled", "5029", "" },
	{ "veh_aiOverSteerScale", "1582", "" },
	{ "veh_boneControllerLodDist", "3878", "Distance at which bone controllers are not updated." },
	{ "vehAudio_inAirPitchDownLerp", "2350", "" },
	{ "vehAudio_inAirPitchUpLerp", "1120", "" },
	{ "vehAudio_spawnVolumeTime", "141", "" },
	{ "vehCam_chaseFD_ADSCamOffset", "vehCam_chaseFD_ADSCamOffset", "" },
	{ "vehCam_chaseFD_ADSVelocityCamOffsetMultAcceleration", "vehCam_chaseFD_ADSVelocityCamOffsetMultAcceleration", "" },
	{ "vehCam_chaseFD_ADSVelocityCamOffsetMultBoostAcceleration", "vehCam_chaseFD_ADSVelocityCamOffsetMultBoostAcceleration", "" },
	{ "vehCam_chaseFD_ADSVelocityCamOffsetMultDeceleration", "vehCam_chaseFD_ADSVelocityCamOffsetMultDeceleration", "" },
	{ "vehCam_chaseFD_camStartLerpDuration", "vehCam_chaseFD_camStartLerpDuration", "" },
	{ "vehCam_chaseFD_camStartMode", "vehCam_chaseFD_camStartMode", "" },
	{ "vehCam_chaseFD_nonADSCamOffset", "vehCam_chaseFD_nonADSCamOffset", "" },
	{ "vehCam_chaseFD_nonADSVelocityCamOffsetMultAcceleration", "vehCam_chaseFD_nonADSVelocityCamOffsetMultAcceleration", "" },
	{ "vehCam_chaseFD_nonADSVelocityCamOffsetMultDeceleration", "vehCam_chaseFD_nonADSVelocityCamOffsetMultDeceleration", "" },
	{ "vehCam_chaseFD_normalSpawnCamOffset", "vehCam_chaseFD_normalSpawnCamOffset", "" },
	{ "vehCam_chaseFD_transitionSpawnCamAngleOffset", "vehCam_chaseFD_transitionSpawnCamAngleOffset", "" },
	{ "vehCam_chaseFD_transitionSpawnCamOffset", "vehCam_chaseFD_transitionSpawnCamOffset", "" },
	{ "vehCam_freeLook", "1293", "" },
	{ "vehCam_mode", "1145", "" },
	{ "vehCam_planeChaseOffset", "vehCam_planeChaseOffset", "" },
	{ "vehCam_splitscreenPlaneChaseOffset", "vehCam_splitscreenPlaneChaseOffset", "" },
	{ "vehHelicopterBoundsRadius", "4301", "" },
	{ "vehHelicopterDecelerationFwd", "3663", "" },
	{ "vehHelicopterDecelerationSide", "555", "" },
	{ "vehHelicopterDecelerationUp", "2633", "" },
	{ "vehHelicopterHeadSwayDontSwayTheTurret", "3520", "" },
	{ "vehHelicopterHoverSpeedThreshold", "1105", "" },
	{ "vehHelicopterInvertUpDown", "5210", "" },
	{ "vehHelicopterJitterJerkyness", "4971", "" },
	{ "vehHelicopterLookaheadTime", "670", "" },
	{ "vehHelicopterMaxAccel", "5759", "" },
	{ "vehHelicopterMaxAccelVertical", "5864", "" },
	{ "vehHelicopterMaxPitch", "4154", "" },
	{ "vehHelicopterMaxRoll", "4093", "" },
	{ "vehHelicopterMaxSpeed", "893", "" },
	{ "vehHelicopterMaxSpeedVertical", "3976", "" },
	{ "vehHelicopterMaxYawAccel", "2928", "" },
	{ "vehHelicopterMaxYawRate", "2342", "" },
	{ "vehHelicopterPitchOffset", "1544", "" },
	{ "vehHelicopterRemoteControlYawRate", "2342", "" },
	{ "vehHelicopterRightStickDeadzone", "975", "" },
	{ "vehHelicopterScaleMovement", "1356", "" },
	{ "vehHelicopterSoftCollisions", "2231", "" },
	{ "vehHelicopterStrafeDeadzone", "1764", "" },
	{ "vehHelicopterTiltFromAcceleration", "2726", "" },
	{ "vehHelicopterTiltFromControllerAxes", "3623", "" },
	{ "vehHelicopterTiltFromDeceleration", "1328", "" },
	{ "vehHelicopterTiltFromFwdAndYaw", "3403", "" },
	{ "vehHelicopterTiltFromFwdAndYaw_VelAtMaxTilt", "3686", "" },
	{ "vehHelicopterTiltFromVelocity", "5472", "" },
	{ "vehHelicopterTiltMomentum", "1703", "" },
	{ "vehHelicopterTiltSpeed", "3249", "" },
	{ "vehHelicopterYawOnLeftStick", "739", "" },
	{ "vehOffroadTransmission", "5012", "" },
	{ "vehTankADSscale", "1686", "" },
	{ "vehUGVPitchTrack", "428", "" },
	{ "vehUGVRollTrack", "104", "" },
	{ "vehUGVWheelInfluence", "2731", "" },
	{ "vehWalkerControlMode", "2261", "" },
	{ "vendor_overhead_update_proximity", "5950", "" },
	{ "vid_height", "vid_height", "" },
	{ "vid_width", "vid_width", "" },
	{ "vid_xpos", "vid_xpos", "" },
	{ "vid_ypos", "vid_ypos", "" },
	{ "virtualLobbyActive", "4017", "" },
	{ "virtualLobbyAllocated", "4835", "" },
	{ "virtualLobbyCommon", "1975", "" },
	{ "virtualLobbyEnabled", "4287", "" },
	{ "virtualLobbyEnabledForZombies", "4404", "" },
	{ "virtualLobbyInCao", "3183", "" },
	{ "virtualLobbyInFiringRange", "2454", "" },
	{ "virtualLobbyMap", "5473", "" },
	{ "virtualLobbyMembers", "1999", "" },
	{ "virtualLobbyOnly", "986", "" },
	{ "virtualLobbyPresentable", "3965", "" },
	{ "virtualLobbyReady", "5666", "" },
	{ "virtualLobbySkipReinit", "virtualLobbySkipReinit", "" },
	{ "virtualLobbySkipReinitEnabled", "virtualLobbySkipReinitEnabled", "" },
	{ "vl_clan_models_loaded", "3784", "" },
	{ "waypointAerialIconMaxSize", "1254", "" },
	{ "waypointAerialIconMinSize", "3441", "" },
	{ "waypointAerialIconScale", "3096", "" },
	{ "waypointDebugDraw", "4610", "" },
	{ "waypointDistFadeRangeMax", "5649", "" },
	{ "waypointDistFadeRangeMin", "5209", "" },
	{ "waypointDistScaleRangeMax", "1739", "" },
	{ "waypointDistScaleRangeMin", "4204", "" },
	{ "waypointDistScaleSmallest", "5561", "" },
	{ "waypointOffscreenCornerRadius", "1684", "" },
	{ "waypointOffscreenDistanceThresholdAlpha", "964", "" },
	{ "waypointOffscreenPadBottom", "1040", "" },
	{ "waypointOffscreenPadLeft", "2463", "" },
	{ "waypointOffscreenPadRight", "833", "" },
	{ "waypointOffscreenPadTop", "1039", "" },
	{ "waypointOffscreenPointerDistance", "5113", "" },
	{ "waypointOffscreenPointerHeight", "1737", "" },
	{ "waypointOffscreenPointerWidth", "4819", "" },
	{ "waypointOffscreenRoundedCorners", "998", "" },
	{ "waypointOffscreenScaleLength", "4579", "" },
	{ "waypointOffscreenScaleSmallest", "5102", "" },
	{ "waypointPlayerOffsetCrouch", "3463", "" },
	{ "waypointPlayerOffsetProne", "3928", "" },
	{ "waypointPlayerOffsetStand", "3848", "" },
	{ "waypointScreenCenterFadeAdsMin", "3253", "" },
	{ "waypointScreenCenterFadeHipMin", "3935", "" },
	{ "waypointScreenCenterFadeRadius", "2587", "" },
	{ "waypointSplitscreenScale", "2865", "" },
	{ "waypointTweakY", "4867", "" },
	{ "wideScreen", "4817", "" },
	{ "win_useWmInput", "win_useWmInput", "" },
	{ "winners_circle_length", "5087", "" },
	{ "winners_circle_skiplisten", "1810", "" },
	{ "winners_circle_timeout", "5660", "" },
	{ "zombiesAllowSoloPause", "5353", "" },
});
}
